### ISSUE TITLE
Error after latest update

### ISSUE THREAD

**Issue by arathak** [zyddnys/manga-image-translator#105]
python translate_demo.py --verbose --mode batch --use-inpainting --manga2eng --force-horizontal --translator=deepl --target-lang=ENG --image w:\test
Traceback (most recent call last):
  File "C:\manga-image-translator\translate_demo.py", line 16, in <module>
    from translators import OFFLINE_TRANSLATORS, TRANSLATORS, VALID_LANGUAGES, dispatch as run_translation, prepare as prepare_translation
  File "C:\manga-image-translator\translators\__init__.py", line 10, in <module>
    from .nnlb import NNLBTranslator, NNLBBigTranslator
  File "C:\manga-image-translator\translators\nnlb.py", line 4, in <module>
    from langdetect import detect
ModuleNotFoundError: No module named 'langdetect'

**Comment by thatDudo** [comment]
run `pip install -r requirements.txt` to install latest dependencies
