### ISSUE TITLE
The code didn't work. (in Colab)

### ISSUE THREAD

**Issue by ji-in0615** [zyddnys/manga-image-translator#119]
Thanks for putting such a good project.

I tried running a code in colab.
It showed error messages.

Traceback (most recent call last):
  File "translate_demo.py", line 13, in <module>
    from detection import dispatch as dispatch_detection, load_model as load_detection_model
  File "/content/manga-image-translator/manga-image-translator/detection/__init__.py", line 6, in <module>
    from utils import Quadrilateral
  File "/content/manga-image-translator/manga-image-translator/utils.py", line 429, in <module>
    class Quadrilateral(object):
  File "/content/manga-image-translator/manga-image-translator/utils.py", line 463, in Quadrilateral
    def fg_colors(self) -> tuple[int, int, int]:
TypeError: 'type' object is not subscriptable

what happens?

**Comment by thatDudo** [comment]
What is your python version?

**Comment by ji-in0615** [comment]
I tried your new code again.
It showed another error messages.

usage: translate_demo.py [-h] [-m {demo,batch,web,web2}] -i IMAGE
                         [-o IMAGE_DST]
                         [-l {CHS,CHT,CSY,NLD,ENG,FRA,DEU,HUN,ITA,JPN,KOR,PLK,PTB,ROM,RUS,ESP,TRK,UKR,VIN}]
                         [-v] [--host HOST] [--port PORT] [--log-web]
                         [--ocr {32px,48px_ctc}]
                         [--inpainter {none,default,lama_mpe}]
                         [--translator {google,youdao,baidu,deepl,papago,none,original,offline,offline_big,nnlb,nnlb_big,sugoi,sugoi_small,sugoi_big}]
                         [--use-cuda] [--use-cuda-limited]
                         [--detection-size DETECTION_SIZE]
                         [--inpainting-size INPAINTING_SIZE]
                         [--unclip-ratio UNCLIP_RATIO]
                         [--box-threshold BOX_THRESHOLD]
                         [--text-threshold TEXT_THRESHOLD]
                         [--text-mag-ratio TEXT_MAG_RATIO]
                         [--font-size-offset FONT_SIZE_OFFSET]
                         [--force-horizontal] [--force-vertical]
                         [--upscale-ratio {1,2,4,8,16,32}] [--use-ctd]
                         [--manga2eng] [--eng-font ENG_FONT]
translate_demo.py: error: the following arguments are required: -i/--image

**Comment by thatDudo** [comment]
If you are trying to use this as a module please open a new issue. Otherwise read the error message - it asks for an image file / directory to be supplied.

**Comment by QiroNT** [comment]
> If you are trying to use this as a module please open a new issue. Otherwise read the error message - it asks for an image file / directory to be supplied.

@thatDudo I suppose web mode doesn't really need an image to be specified?

**Comment by thatDudo** [comment]
ugh, youre right sorry

**Comment by QiroNT** [comment]
Done, thanks for the contribution anyways!
