### ISSUE TITLE
Error during translation

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#123]
I have started server in docker container and after image upload I see error  on UI and 
> Something went wrong (maybe your language is not supported), please try again

in logs:

```
2022-11-16 17:01:22 | INFO | aiohttp.access | 127.0.0.1 [16/Nov/2022:17:01:22 +0000] "GET /task-internal?nonce=9fa6e4ecc06ed3acdec12c84af4b2d76 HTTP/1.1" 200 158 "-" "python-requests/2.27.1"
Traceback (most recent call last):
  File "/app/translate_demo.py", line 283, in infer_safe
    return await infer(
TypeError: infer() takes from 2 to 6 positional arguments but 7 were given
Task state fa4a1abd955ae185d950c76a2543c326ca343497b1eecb0e627e2637cea8666c-M-google-RUS-default-auto to error
```

same for deepl
```
2022-11-16 17:01:48 | INFO | aiohttp.access | 127.0.0.1 [16/Nov/2022:17:01:48 +0000] "GET /task-internal?nonce=9fa6e4ecc06ed3acdec12c84af4b2d76 HTTP/1.1" 200 400 "-" "python-requests/2.27.1"
 -- Processing task fa4a1abd955ae185d950c76a2543c326ca343497b1eecb0e627e2637cea8666c-M-deepl-RUS-default-auto
2022-11-16 17:01:48 | INFO | aiohttp.access | 127.0.0.1 [16/Nov/2022:17:01:48 +0000] "GET /task-internal?nonce=9fa6e4ecc06ed3acdec12c84af4b2d76 HTTP/1.1" 200 158 "-" "python-requests/2.27.1"
Traceback (most recent call last):
  File "/app/translate_demo.py", line 283, in infer_safe
    return await infer(
TypeError: infer() takes from 2 to 6 positional arguments but 7 were given
Task state fa4a1abd955ae185d950c76a2543c326ca343497b1eecb0e627e2637cea8666c-M-deepl-RUS-default-auto to error
```

my parameters is:

```
    command: --verbose --log-web --translator=deepl --target-lang=ENG --manga2eng --mode web --host=0.0.0.0 --port=5055
```

In what direction I should digg???

**Comment by rspreet92** [comment]
try without translator argument

**Comment by thatDudo** [comment]
Fixed it just now. Thanks for sending your error message as well :+1:
