### ISSUE TITLE
Error arithm.cpp:647 during rendering with custom font

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#126]
```
192 83 113 74
font_size: 47
['ХАХА,', 'КАКОЙ', 'ИНТЕРЕСН-', 'ЫЙ', 'ПЕРСОНАЖ.'] [157, 214, 361, 80, 362]
HAH?
ХАХ?
520 1160 68 33
font_size: 79
['ХАХ?'] [237]
WHY DID-YOU SUDDENLY TURN INTO. A TOTAL DICK?
ПОЧЕМУ ТЫ ВДРУГ ПРЕВРАТИЛСЯ В. В ПОЛНОГО ПРИДУРКА?
608 1193 271 39
font_size: 47
['ПОЧЕМУ ТЫ ВДРУГ ПРЕВРАТИЛ-', 'СЯ В. В ПОЛНОГО ПРИДУРКА?'] [944, 877]
个腾讯动漫 ac.aa.caM
个腾讯动漫 ac.aa.caM
804 1238 110 36
font_size: 47
['个腾讯动漫', 'ac.aa.caM'] [235, 332]
HEY KID! YOUR ELDER'S ASKING YOU A QUESTION.
ЭЙ, МАЛЫШ! ТВОЙ СТАРЕЙШИНА ЗАДАЕТ ТЕБЕ ВОПРОС.
400 425 159 71
font_size: 79
['ЭЙ, МАЛЫШ! ТВОЙ', 'СТАРЕЙШИНА', 'ЗАДАЕТ ТЕБЕ', 'ВОПРОС.'] [879, 659, 712, 462]
Traceback (most recent call last):
  File "/app/translate_demo.py", line 282, in infer_safe
    return await infer(
  File "/app/translate_demo.py", line 263, in infer
    output = await dispatch_rendering(np.copy(img_inpainted), args.text_mag_ratio, translated_sentences, textlines, text_regions, render_text_direction_overwrite, args.target_lang, args.font_size_offset)
  File "/app/text_rendering/__init__.py", line 65, in dispatch
    img_canvas = render(img_canvas, font_size, text_mag_ratio, trans_text, region, majority_dir, fg, bg, False, font_size_offset)
  File "/app/text_rendering/__init__.py", line 119, in render
    temp_box = text_render.put_text_horizontal(
  File "/app/text_rendering/text_render.py", line 497, in put_text_horizontal
    offset_x = put_char_horizontal(font_size, rot, t, pen_line, canvas_text, canvas_border, border_size=bgsize)
  File "/app/text_rendering/text_render.py", line 471, in put_char_horizontal
    canvas_border[pen_border[1]:pen_border[1]+bitmap_b.rows, pen_border[0]:pen_border[0]+bitmap_b.width] = cv2.add(canvas_border[pen_border[1]:pen_border[1]+bitmap_b.rows, pen_border[0]:pen_border[0]+bitmap_b.width], bitmap_border)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/core/src/arithm.cpp:647: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'
```

happance for that images translations. Any ideas?
![0011](https://user-images.githubusercontent.com/20344446/203147580-6f5487c2-d36e-4795-a268-a184ffd8aa7c.png)
![0006](https://user-images.githubusercontent.com/20344446/203147586-5d05f63d-c4aa-42bf-b369-0d939228d3f2.png)
![0002](https://user-images.githubusercontent.com/20344446/203147588-2c2f4991-93ed-4a62-871f-09017d0e0f41.png)

**Comment by purpleraven** [comment]
can it be an issue of custom font?

**Comment by zyddnys** [comment]
I was unable to reproduce this error, can you share your exact parameters? e.g. detection resolution, translator

**Comment by purpleraven** [comment]
@zyddnys 

I'm  using web version with followingparameters
```
command: --verbose --translator=deepl --mode web --host=0.0.0.0 --port=5055 --font-size-offset=10 --unclip-ratio=2
```

**Comment by purpleraven** [comment]
@zyddnys any updates?

**Comment by zyddnys** [comment]
no luck preproducing this error

**Comment by purpleraven** [comment]
@zyddnys 

with new version of docker image I can reproduce it without custom build on first test image

```
  command: --verbose --translator=deepl --mode web --host=0.0.0.0 --port=5055 --upscale-ratio=1 --font-size-offset=10 --unclip-ratio=2 --font-path=fonts/anime_ace.ttf
...
volumes:
      - /home/translate/fonts:/app/fonts
```

for both fonts version same problem.
[anime_ace.zip](https://github.com/zyddnys/manga-image-translator/files/10697414/anime_ace.zip)

```
['ДАВАЙТЕ', 'ПОКА', 'ПОТРЕНИ-', 'РУЕМСЯ С', 'МУНДШТ-', 'УКОМ.'] [412, 282, 501, 472, 485, 277]
Traceback (most recent call last):
  File "/app/translate_demo.py", line 247, in infer_safe
    return await infer(
  File "/app/translate_demo.py", line 223, in infer
    output = await dispatch_rendering(np.copy(img_inpainted), args.text_mag_ratio, text_regions, render_text_direction_overwrite, args.font_path, args.font_size_offset, render_mask, img_rgb)
  File "/app/text_rendering/__init__.py", line 88, in dispatch
    img = render(img, region, font_size, text_mag_ratio, majority_dir, fg, bg, original_img, font_size_offset, render_mask)
  File "/app/text_rendering/__init__.py", line 127, in render
    temp_box = text_render.put_text_horizontal(
  File "/app/text_rendering/text_render.py", line 501, in put_text_horizontal
    offset_x = put_char_horizontal(font_size, c, pen_line, canvas_text, canvas_border, border_size=bg_size)
  File "/app/text_rendering/text_render.py", line 477, in put_char_horizontal
    canvas_border[pen_border[1]:pen_border[1]+bitmap_b.rows, pen_border[0]:pen_border[0]+bitmap_b.width] = cv2.add(canvas_border[pen_border[1]:pen_border[1]+bitmap_b.rows, pen_border[0]:pen_border[0]+bitmap_b.width], bitmap_border)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/core/src/arithm.cpp:647: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'
```
![0001](https://user-images.githubusercontent.com/20344446/217820841-e0c04547-20a1-41bf-95cd-d0b9d9e7d44f.png)

**Comment by thatDudo** [comment]
Looks like the problem appeared with `--target-lang RUS`. The pen coordinates were negative so the renderer tried to draw into negative pixel coordinates.

**Comment by purpleraven** [comment]
@thatDudo have you include fix to latest docker image?
