### ISSUE TITLE
Permission denied: '/app/models/waifu2x-linux/waifu2x-ncnn-vulkan'

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#127]
От standard docker image I see error in log (started on usual server without video card):

```
2022-11-21 20:28:06 | INFO | aiohttp.access | 127.0.0.1 [21/Nov/2022:20:28:06 +0000] "POST /task-update-internal HTTP/1.1" 200 158 "-" "python-requests/2.27.1"
Traceback (most recent call last):
  File "/app/translate_demo.py", line 283, in infer_safe
    return await infer(
  File "/app/translate_demo.py", line 146, in infer
    img_upscaled_pil = (await dispatch_upscaling('waifu2x', [image], ratio, args.use_cuda))[0]
  File "/app/upscaling/__init__.py", line 35, in dispatch
    return await upscaler.upscale(image_batch, upscale_ratio)
  File "/app/upscaling/common.py", line 17, in upscale
    return await self._upscale(image_batch, upscale_ratio)
  File "/app/upscaling/common.py", line 26, in _upscale
    return await self.forward(*args, **kwargs)
  File "/app/utils.py", line 315, in forward
    return await self._forward(*args, **kwargs)
  File "/app/upscaling/waifu2x.py", line 64, in _forward
    self._run_waifu2x_executable(in_dir, out_dir, upscale_ratio, 0)
  File "/app/upscaling/waifu2x.py", line 91, in _run_waifu2x_executable
    subprocess.check_call(cmds)
  File "/opt/conda/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/conda/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/conda/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/app/models/waifu2x-linux/waifu2x-ncnn-vulkan'
```

**Comment by thatDudo** [comment]
Cant reproduce. Is this exception persistent across every run or did it happen right after download of the models? Also, how did you have you gotten to post the previous issue #126 if this exception should have appeared beforehand?

**Comment by ji-in0615** [comment]
me too. when I run 'translate_demo.py' code, It's not working with that error message.

**Comment by purpleraven** [comment]
I see it for some pages. usually on cover pages with 2 languages

**Comment by purpleraven** [comment]
for example it fails on the image:
![62a9d289-40c1-483d-81f7-e3ca4b383b71](https://user-images.githubusercontent.com/20344446/203407914-6adc4fce-f03b-48d8-aec4-8b73843119ad.png)

**Comment by QiroNT** [comment]
Implemented a simple permission check, let me know if it's fixed!
