### ISSUE TITLE
Translation is failed when using docker

### ISSUE THREAD

**Issue by kkbpower** [zyddnys/manga-image-translator#130]
I deployed with docker compose.
And then i accessed web and then test with image. But I got this error message 

```
manga_image_translator_gpu  | New `submit` task d54abe601f1c164299865da1999e479cd043999676634b0fe47968e7e4f2f06b-M-google-KOR-default-auto
manga_image_translator_gpu  |  -- Processing task d54abe601f1c164299865da1999e479cd043999676634b0fe47968e7e4f2f06b-M-google-KOR-default-auto
manga_image_translator_gpu  |  -- Detection resolution 1536
manga_image_translator_gpu  |  -- Detector using default
manga_image_translator_gpu  |  -- Render text direction is auto
manga_image_translator_gpu  |  -- Preparing translator
manga_image_translator_gpu  |  -- Preparing upscaling
manga_image_translator_gpu  |  -- Running upscaling
manga_image_translator_gpu  | Task state d54abe601f1c164299865da1999e479cd043999676634b0fe47968e7e4f2f06b-M-google-KOR-default-auto to upscaling
manga_image_translator_gpu  | /app/models/waifu2x-linux/waifu2x-ncnn-vulkan: error while loading shared libraries: libvulkan.so.1: cannot open shared object file: No such file or directory
manga_image_translator_gpu  | Traceback (most recent call last):
manga_image_translator_gpu  |   File "/app/translate_demo.py", line 283, in infer_safe
manga_image_translator_gpu  |     return await infer(
manga_image_translator_gpu  |   File "/app/translate_demo.py", line 147, in infer
manga_image_translator_gpu  |     img_upscaled_pil = (await dispatch_upscaling('waifu2x', [image], ratio, args.use_cuda))[0]
manga_image_translator_gpu  |   File "/app/upscaling/__init__.py", line 35, in dispatch
manga_image_translator_gpu  |     return await upscaler.upscale(image_batch, upscale_ratio)
manga_image_translator_gpu  |   File "/app/upscaling/common.py", line 17, in upscale
manga_image_translator_gpu  |     return await self._upscale(image_batch, upscale_ratio)
manga_image_translator_gpu  |   File "/app/upscaling/common.py", line 26, in _upscale
manga_image_translator_gpu  |     return await self.forward(*args, **kwargs)
manga_image_translator_gpu  |   File "/app/utils.py", line 338, in forward
manga_image_translator_gpu  |     return await self._forward(*args, **kwargs)
manga_image_translator_gpu  |   File "/app/upscaling/waifu2x.py", line 67, in _forward
manga_image_translator_gpu  |     self._run_waifu2x_executable(in_dir, out_dir, upscale_ratio, 0)
manga_image_translator_gpu  |   File "/app/upscaling/waifu2x.py", line 92, in _run_waifu2x_executable
manga_image_translator_gpu  |     subprocess.check_call(cmds)
manga_image_translator_gpu  |   File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
manga_image_translator_gpu  |     raise CalledProcessError(retcode, cmd)
manga_image_translator_gpu  | subprocess.CalledProcessError: Command '['/app/models/waifu2x-linux/waifu2x-ncnn-vulkan', '-i', '/tmp/tmp4ou8jfmp', '-o', '/tmp/tmpok5pw82w', '-m', '/app/models/waifu2x-linux/models-cunet', '-s', '4', '-n', '0']' returned non-zero exit status 127.
manga_image_translator_gpu  | Task state d54abe601f1c164299865da1999e479cd043999676634b0fe47968e7e4f2f06b-M-google-KOR-default-auto to error
```
What is wrong?

**Comment by purpleraven** [comment]
right. 
Anyway after https://github.com/zyddnys/manga-image-translator/issues/127 the code fails on some images (not for every)

```
subprocess.CalledProcessError: Command '['/app/models/waifu2x-linux/waifu2x-ncnn-vulkan', '-i', '/tmp/tmpqoijrrtx', '-o', '/tmp/tmpsn3qx4j5', '-m', '/app/models/waifu2x-linux/models-cunet', '-s', '4', '-n', '0']' returned non-zero exit status 127.
 -- Processing task f8e2b645c34d4f58bc27e0fb85d4c5a2927ce52c01f668f87c23071f69489ce5--deepl-RUS-default-auto
 -- Detection resolution 1536
 -- Detector using default
 -- Render text direction is auto
 -- Preparing translator
 -- Preparing upscaling
 -- Running upscaling
/app/models/waifu2x-linux/waifu2x-ncnn-vulkan: error while loading shared libraries: libvulkan.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/app/translate_demo.py", line 283, in infer_safe
    return await infer(
  File "/app/translate_demo.py", line 147, in infer
    img_upscaled_pil = (await dispatch_upscaling('waifu2x', [image], ratio, args.use_cuda))[0]
  File "/app/upscaling/__init__.py", line 35, in dispatch
    return await upscaler.upscale(image_batch, upscale_ratio)
  File "/app/upscaling/common.py", line 17, in upscale
    return await self._upscale(image_batch, upscale_ratio)
  File "/app/upscaling/common.py", line 26, in _upscale
    return await self.forward(*args, **kwargs)
  File "/app/utils.py", line 338, in forward
    return await self._forward(*args, **kwargs)
  File "/app/upscaling/waifu2x.py", line 67, in _forward
    self._run_waifu2x_executable(in_dir, out_dir, upscale_ratio, 0)
  File "/app/upscaling/waifu2x.py", line 92, in _run_waifu2x_executable
    subprocess.check_call(cmds)
  File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/app/models/waifu2x-linux/waifu2x-ncnn-vulkan', '-i', '/tmp/tmp3jlf8g6f', '-o', '/tmp/tmpvr7x5rh0', '-m', '/app/models/waifu2x-linux/models-cunet', '-s', '4', '-n', '0']' returned non-zero exit status 127.

```

**Comment by thatDudo** [comment]
This problem seems to have been fixed in #131 with by installing libgl1-mesa-glx.

**Comment by purpleraven** [comment]
@thatDudo how fast new image will be published in dockerhub?

**Comment by thatDudo** [comment]
Depends on how quickly @QiroNT will react.

**Comment by zyddnys** [comment]
new docker image created

**Comment by purpleraven** [comment]
@zyddnys same

```
subprocess.CalledProcessError: Command '['/app/models/waifu2x-linux/waifu2x-ncnn-vulkan', '-i', '/tmp/tmpah56b2p8', '-o', '/tmp/tmpn5588hri', '-m', '/app/models/waifu2x-linux/models-cunet', '-s', '4', '-n', '0']' returned non-zero exit status 127.
 -- Processing task faaae430be44b5cbc0351c9ca5d56a59311e4fca9585ca4791b5e43a9fd83389--deepl-RUS-default-auto
 -- Detection resolution 1536
 -- Detector using default
 -- Render text direction is auto
 -- Preparing translator
 -- Preparing upscaling
 -- Running upscaling
/app/models/waifu2x-linux/waifu2x-ncnn-vulkan: error while loading shared libraries: libvulkan.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/app/translate_demo.py", line 283, in infer_safe
    return await infer(
  File "/app/translate_demo.py", line 147, in infer
    img_upscaled_pil = (await dispatch_upscaling('waifu2x', [image], ratio, args.use_cuda))[0]
  File "/app/upscaling/__init__.py", line 35, in dispatch
    return await upscaler.upscale(image_batch, upscale_ratio)
  File "/app/upscaling/common.py", line 17, in upscale
    return await self._upscale(image_batch, upscale_ratio)
  File "/app/upscaling/common.py", line 26, in _upscale
    return await self.forward(*args, **kwargs)
  File "/app/utils.py", line 338, in forward
    return await self._forward(*args, **kwargs)
  File "/app/upscaling/waifu2x.py", line 67, in _forward
    self._run_waifu2x_executable(in_dir, out_dir, upscale_ratio, 0)
  File "/app/upscaling/waifu2x.py", line 92, in _run_waifu2x_executable
    subprocess.check_call(cmds)
  File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/app/models/waifu2x-linux/waifu2x-ncnn-vulkan', '-i', '/tmp/tmp0n62wh7g', '-o', '/tmp/tmp0b00x8d6', '-m', '/app/models/waifu2x-linux/models-cunet', '-s', '4', '-n', '0']' returned non-zero exit status 127.

```

**Comment by zyddnys** [comment]
Try the new docker image

**Comment by ryanolee** [comment]
It looks like it is trying to use the vulkan API to upscale inside the docker container. Do you have GPU support enabled in the container? 

https://github.com/zyddnys/manga-image-translator#using-with-nvida-gpu

Docker GPU support is limited to Nvidia cards. You need the Nvidia Docker Toolkit to add in support @thatDudo @zyddnys Is it possible to run `waifu2x` on the CPU. If not might be making the `--use-cuda` option mandatory before using waifu2x for upscaling? 
(Given we have errors if a GPU is not detected https://github.com/zyddnys/manga-image-translator/blob/de53e75efd5f2a05cc0584a218166cc37553d516/translate_demo.py#L305)  If not I guess we can just add waifu2x to that check 🤔

**Comment by purpleraven** [comment]
@ryanolee i have no --use-cuda in arguments 

```
    image: zyddnys/manga-image-translator:main      
    restart: unless-stopped
    container_name: manga-translator
    command: --verbose --translator=deepl --mode web --host=0.0.0.0 --port=5055 --font-size-offset=10 --unclip-ratio=2
```

**Comment by ryanolee** [comment]
I think there is likely a bug where waifu 2x  (Which relies on CUDA) is used irrespective of if `--use-cuda` option or not. I think the resolution this this will probably be making the wafu 2x Upscaling optional @zyddnys  @thatDudo  through either a new CLI argument or by disabling it if the --use-cuda is not explicitly given :thinking:  (And making sure the error I raised above is thrown if it is set)

**Comment by thatDudo** [comment]
You can disable waifu2x with `--upscale-ratio=1`. I had problems deciding whether to make it dependent on `--use-cuda` because it uses vulkan and should therefore be able to work on non nvidia gpus. The waifu2x executable selects the device automatically so if you are still getting this error it seems likely that you have in fact a gpu on your system. Have you updated to the new docker image? I though @zyddnys had added the neccessary dependency that should fix this issue.

**Comment by purpleraven** [comment]
with --upscale-ratio=1 works without error.

**Comment by zyddnys** [comment]
Maybe we can catch waifu2x error and display a warning instead

**Comment by purpleraven** [comment]
@zyddnys can be closed
