### ISSUE TITLE
error offline using windows 11

### ISSUE THREAD

**Issue by kucingkembar** [zyddnys/manga-image-translator#139]
hi, sorry for my bad english
i use windows 11, python 310
when using offline mode, it error
```
C:\Users\GIGABYTE>cd /d E:\manga-image-translator
E:\manga-image-translator>python translate_demo.py --verbose --translator=offline --target-lang=ENG --image C:\Users\GIGABYTE\Desktop\eat\download\009\3.png
Namespace(mode='demo', image='C:\\Users\\GIGABYTE\\Desktop\\eat\\download\\009\\3.png', image_dst='', target_lang='ENG', verbose=True, host='127.0.0.1', port=5003, log_web=False, ocr='48px_ctc', inpainter='lama_mpe', translator='offline', use_cuda=False, use_cuda_limited=False, detection_size=1536, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, text_mag_ratio=1, font_size_offset=0, force_horizontal=False, force_vertical=False, upscale_ratio=None, use_ctd=False, manga2eng=False, eng_font='fonts/comic shanns 2.ttf')
 -- Preload Checks
 -- Loading models
 -- Running in single image demo mode
 -- Detection resolution 1536
 -- Detector using default
 -- Render text direction is auto
 -- Preparing translator
 -- Preparing upscaling
 -- Running upscaling
[0 NVIDIA GeForce GTX 1660 SUPER]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1660 SUPER]  bugsbn1=0  bugbilz=51  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1660 SUPER]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1660 SUPER]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
 -- Running text detection
Detection resolution: 1280x1536
 -- Running OCR
------------------------------
世: 0.9999960661089133
子: 0.9999487426325072
！: 0.9994326474291275
------------------------------
そ: 0.9999395645427589
ろ: 0.9999988079084972
そ: 0.9999650728993075
ろ: 0.9999986886995842
------------------------------
私: 1.0
も: 0.9999935627400018
我: 0.9999998807907247
慢: 1.0
の: 0.9999998807907247
限: 0.9999998807907247
界: 0.9999996423722521
だ: 0.9999955892755635
------------------------------
国: 0.9996509578637115
境: 0.9999815229018083
の: 1.0
な: 0.9998477929052435
い: 0.9999911785905904
楽: 0.9999907017622996
し: 0.9998875982730323
み: 0.9999920130413283
------------------------------
絶: 1.0
対: 0.9999957084838798
に: 0.9999997615814777
許: 0.9999974966112362
さ: 0.9999606624830781
れ: 0.9999986886995842
な: 0.9999624504845601
い: 0.9999949932351057
------------------------------
今: 0.9999971389852362
年: 1.0
の: 1.0
内: 0.9996265376028781
に: 0.9999996423722521
決: 0.9999963045256735
断: 0.9999983310727032
せ: 0.9999849798550975
よ: 0.9999939203633587
------------------------------
跡: 1.0
継: 1.0
ぎ: 0.9999963045256735
を: 0.9999986886995842
絶: 0.9999997615814777
や: 0.999977350747961
す: 0.9999538681349789
な: 0.9985389629265963
ど: 0.999985933501902
0.9997924528221414 世子！ fg: (1, 0, 1) bg: (0, 1, 1)
0.9999755332023961 そろそろ fg: (0, 0, 1) bg: (0, 0, 0)
0.9999985545922271 私も我慢の限界だ fg: (0, 0, 3) bg: (0, 0, 3)
0.9999177141633738 国境のない楽しみ fg: (64, 42, 43) bg: (62, 40, 43)
0.999988720072921 絶対に許されない fg: (0, 0, 0) bg: (0, 0, 0)
0.999955199323479 今年の内に決断せよ fg: (0, 0, 0) bg: (0, 0, 0)
0.999827770426052 跡継ぎを絶やすなど fg: (0, 0, 1) bg: (0, 0, 1)
 -- spliting {0, 4, 6}
to split [0, 4, 6]
edge_weights [185.02432272541898, 175.025712396779]
std: 4.999305164319992, mean: 180.025017561099
 -- spliting {1, 2, 5}
to split [1, 2, 5]
edge_weights [180.01111076819674, 172.14238292762187]
std: 3.9343639202874385, mean: 176.0767468479093
 -- spliting {3}
to split [3]
region_indices [{0, 4, 6}, {1, 2, 5}, {3}]
 -- Generating text mask
100%|████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00,  7.97it/s]
 -- Running inpainting
Inpainting resolution: 1560x2048
 -- Translating
 -- Selected translator: SugoiTranslator
2022-12-19 04:56:34 | INFO | fairseq.file_utils | loading archive file E:\manga-image-translator\models\translators\jparacrawl/
2022-12-19 04:56:34 | INFO | fairseq.file_utils | loading archive file E:\manga-image-translator\models\translators\jparacrawl/
Traceback (most recent call last):
  File "E:\manga-image-translator\translate_demo.py", line 394, in <module>
    loop.run_until_complete(main(args.mode))
  File "C:\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "E:\manga-image-translator\translate_demo.py", line 323, in main
    await infer(Image.open(args.image), mode)
  File "E:\manga-image-translator\translate_demo.py", line 227, in infer
    translated_sentences = await dispatch_translation(translator, src_lang, tgt_lang, queries, use_cuda = args.use_cuda and not args.use_cuda_limited)
  File "E:\manga-image-translator\translators\__init__.py", line 91, in dispatch
    result = await asyncio.create_task(translator.translate(src_lang, tgt_lang, queries))
  File "E:\manga-image-translator\translators\selective.py", line 71, in translate
    await self._real_translator.load(*self._cached_load_params)
  File "E:\manga-image-translator\translators\common.py", line 62, in load
    return await super().load(device, *self.parse_language_codes(from_lang, to_lang))
  File "E:\manga-image-translator\utils.py", line 330, in load
    await self._load(*args, **kwargs, device=device)
  File "E:\manga-image-translator\translators\sugoi.py", line 61, in _load
    self.model = TransformerModel.from_pretrained(
  File "C:\Python\Python310\lib\site-packages\fairseq\models\fairseq_model.py", line 267, in from_pretrained
    x = hub_utils.from_pretrained(
  File "C:\Python\Python310\lib\site-packages\fairseq\hub_utils.py", line 73, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "C:\Python\Python310\lib\site-packages\fairseq\checkpoint_utils.py", line 423, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: E:\manga-image-translator\models\translators\jparacrawl/base.pretrain.ja-en.pt
```
my prediction is this "/" in "/base.pretrain.ja-en.pt" because you write in linux OS, when i use windows OS that use "\\", the error triggered

**Comment by thatDudo** [comment]
Can you manually check whether file exists or not? Normally paths with "/" shouldnt be a problem on windows.

**Comment by kucingkembar** [comment]
sorry for the late reply,
the folder is empty,
do I need to manually download it?
any tutorial or link?

**Comment by thatDudo** [comment]
It should have automatically downloaded it. Can you rerun translate_demo.py and if it still doesnt work run `python docker_prepare.py`?

**Comment by kucingkembar** [comment]
i use it using --translator=google, no problem
it appear when using --translator=offline
i dont use docker (i dont understood how to use it)

**Comment by thatDudo** [comment]
I think I have found the bug. It should be fixed now

**Comment by kucingkembar** [comment]
thank for the hard work
```
Downloading: "http://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/release/3.0/pretrained_models/ja-en/base.tar.gz"
base.tar.gz:   2%|█▍                                                           | 21.3M/898M [04:59<28:34:53, 8.93kiB/s]
```
currently my download speed is not so good, I will reply it when it done

**Comment by kucingkembar** [comment]
after some time, the download speed increased to 600kbps, 
and all problem is solved,
thank you for the great software, you can close it

**Comment by thatDudo** [comment]
Thanks for your help too :ok_hand:
