### ISSUE TITLE
TypeError in manual translation - localhost:5003/manual

### ISSUE THREAD

**Issue by tak2hu** [zyddnys/manga-image-translator#225]
```
[web] -- Running text detection
Task state d8de2921496c9057b2dffbcc93687df4 to {'info': 'detection', 'finished': False}
Task state d8de2921496c9057b2dffbcc93687df4 to {'info': 'error', 'finished': True}
ERROR: [web] TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/kys/Git/manga-image-translator/manga_translator/manga_translator.py", line 164, in translate
    return await self._translate(image, params)
  File "/home/kys/Git/manga-image-translator/manga_translator/manga_translator.py", line 188, in _translate
    text_regions, mask_raw, mask = await self._run_detection(params.detector, img_rgb, params.detection_size, params.text_threshold,
  File "/home/kys/Git/manga-image-translator/manga_translator/manga_translator.py", line 283, in _run_detection
    return await dispatch_detection(key, img, detect_size, text_threshold, box_threshold, unclip_ratio, det_rearrange_max_batches,
  File "/home/kys/Git/manga-image-translator/manga_translator/detection/__init__.py", line 33, in dispatch
    return await detector.detect(image, detect_size, text_threshold, box_threshold, unclip_ratio, det_rearrange_max_batches, verbose)
  File "/home/kys/Git/manga-image-translator/manga_translator/detection/common.py", line 20, in detect
    bordered_image_size = detect_size // 2
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
Error handling request
Traceback (most recent call last):
  File "/home/kys/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/kys/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/kys/Git/manga-image-translator/manga_translator/server/web_main.py", line 80, in result_async
    im = Image.open("result/" + request.match_info.get('taskid') + "/final.png")
  File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'result/d8de2921496c9057b2dffbcc93687df4/final.png'
```

when I tap the submit button, the image goes away

**Comment by tak2hu** [comment]
Oh it works now, thanks!

**Comment by thatDudo** [comment]
Yeah it had to do with the refactoring we have been doing last week or so. :laughing:
