### ISSUE TITLE
Error during translation with custom fonts

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#228]
Russian lang have been used
```
[rendering] font_size: 42
ERROR: [web] ValueError: could not broadcast input array from shape (44,28) into shape (0,28)
Traceback (most recent call last):
  File "/app/manga_translator/manga_translator.py", line 164, in translate
    return await self._translate(image, params)
  File "/app/manga_translator/manga_translator.py", line 231, in _translate
    output = await self._run_text_rendering(params.renderer, img_inpainted, text_regions, params.text_mag_ratio, params.direction,
  File "/app/manga_translator/manga_translator.py", line 315, in _run_text_rendering
    output = await dispatch_rendering(img, text_regions, text_mag_ratio, text_direction, font_path, font_size_offset, original_img, mask)
  File "/app/manga_translator/text_rendering/__init__.py", line 95, in dispatch
    img = render(img, region, font_size, text_mag_ratio, majority_dir, fg, bg, original_img, font_size_offset, render_mask)
  File "/app/manga_translator/text_rendering/__init__.py", line 134, in render
    temp_box = text_render.put_text_horizontal(
  File "/app/manga_translator/text_rendering/text_render.py", line 505, in put_text_horizontal
    offset_x = put_char_horizontal(font_size, c, pen_line, canvas_text, canvas_border, border_size=bg_size)
  File "/app/manga_translator/text_rendering/text_render.py", line 466, in put_char_horizontal
    canvas_text[pen[1]:pen[1]+bitmap.rows, pen[0]:pen[0]+bitmap.width] = bitmap_char
ValueError: could not broadcast input array from shape (44,28) into shape (0,28)

```

**Comment by thatDudo** [comment]
Can you share the image and/or font used?

**Comment by purpleraven** [comment]
Sure, with new log file that become simple:

[example.zip](https://github.com/zyddnys/manga-image-translator/files/10843512/example.zip)

```
command: --verbose --translator=deepl --mode web --host=0.0.0.0 --port=5055 --upscale-ratio=1 --font-size-offset=10 --unclip-ratio=2 --font-path=fonts/anime_ace.ttf
```

Now I have around 23 files from 180 with the error

**Comment by purpleraven** [comment]
@thatDudo with latest docker image the error is same
