### ISSUE TITLE
ERROR: [batch] AttributeError: 'Model48pxCTCOCR' object has no attribute 'model'

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#238]
[batch] Processing F:\Mangas\Oyasumi\1\038.webp -> F:\Mangas\Oyasumi\1-translated\038.webp
[batch] Loading models
ERROR: [batch] AttributeError: 'Model48pxCTCOCR' object has no attribute 'model'
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 167, in translate
    await prepare_ocr(params.ocr, self.device)
  File "F:\manga-image-translator\manga_translator\ocr\__init__.py", line 24, in prepare
    ocr = get_ocr(ocr_key)
  File "F:\manga-image-translator\manga_translator\ocr\__init__.py", line 20, in get_ocr
    ocr_cache[key] = ocr(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\ocr\model_48px_ctc.py", line 29, in __init__
    os.makedirs(self.model, exist_ok=True)
AttributeError: 'Model48pxCTCOCR' object has no attribute 'model'

**Comment by thatDudo** [comment]
Thanks for putting up with my mistakes .-.
