### ISSUE TITLE
ERROR: [batch] OSError: [WinError -1073741818] Windows Error 0xc0000006

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#241]
ERROR: [batch] OSError: [WinError -1073741818] Windows Error 0xc0000006
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 181, in translate
    return await self._translate(image, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 259, in _translate
    output = await self._run_text_rendering(params.renderer, img_inpainted, text_regions, params.text_mag_ratio, params.direction,
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 349, in _run_text_rendering
    output = await dispatch_rendering(img, text_regions, text_mag_ratio, font_path, font_size_offset, font_size_minimum, rearrange_regions, mask)
  File "F:\manga-image-translator\manga_translator\text_rendering\__init__.py", line 135, in dispatch
    line_text_list, line_width_list = text_render.calc_horizontal(font_size, region.translation, enlarged_w)
  File "F:\manga-image-translator\manga_translator\text_rendering\text_render.py", line 360, in calc_horizontal
    glyph = get_char_glyph(cdpt, font_size, 0)
  File "F:\manga-image-translator\manga_translator\text_rendering\text_render.py", line 207, in get_char_glyph
    face.load_char(cdpt)
  File "F:\1\envs\Mt\lib\site-packages\freetype\__init__.py", line 1546, in load_char
    error = FT_Load_Char( self._FT_Face, char, flags )
OSError: [WinError -1073741818] Windows Error 0xc0000006

**Comment by thatDudo** [comment]
Does this error appear consistently or only with a specific font/image. May be a problem with you dependencies.
`pip install freetype-py --force-reinstall -U`
