### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by HolzerDavid** [zyddnys/manga-image-translator#243]
I tried up/downgrading cuda and pytorch, but i keep getting this type error

### Traceback
ERROR: [web] TypeError: '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "P:\manga-image-translator\manga_translator\manga_translator.py", line 181, in translate
    return await self._translate(image, params)
  File "P:\manga-image-translator\manga_translator\manga_translator.py", line 243, in _translate
    translated_sentences = await self._run_text_translation(params.translator, 'auto', params.target_lang,
  File "P:\manga-image-translator\manga_translator\manga_translator.py", line 477, in _run_text_translation
    return await super()._run_text_translation(key, src_lang, tgt_lang, text_regions, use_mtpe)
  File "P:\manga-image-translator\manga_translator\manga_translator.py", line 339, in _run_text_translation
    return await dispatch_translation(key, src_lang, tgt_lang, [r.get_text() for r in text_regions], use_mtpe,
  File "P:\manga-image-translator\manga_translator\translators\__init__.py", line 86, in dispatch
    return await translator.translate(src_lang, tgt_lang, queries, use_mtpe)
  File "P:\manga-image-translator\manga_translator\translators\selective.py", line 74, in translate
    return await self._real_translator.translate(from_lang, to_lang, queries, use_mtpe)
  File "P:\manga-image-translator\manga_translator\translators\common.py", line 79, in translate
    result = await self._translate(*self.parse_language_codes(from_lang, to_lang, fatal=True), queries)
  File "P:\manga-image-translator\manga_translator\translators\common.py", line 140, in _translate
    return await self.forward(*args, **kwargs)
  File "P:\manga-image-translator\manga_translator\utils\inference.py", line 329, in forward
    return await self._forward(*args, **kwargs)
  File "P:\manga-image-translator\manga_translator\translators\nllb.py", line 74, in _forward
    return [self._translate_sentence(from_lang, to_lang, query) for query in queries]
  File "P:\manga-image-translator\manga_translator\translators\nllb.py", line 74, in <listcomp>
    return [self._translate_sentence(from_lang, to_lang, query) for query in queries]
  File "P:\manga-image-translator\manga_translator\translators\nllb.py", line 90, in _translate_sentence
    translator = pipeline('translation',
  File "C:\Users\Main\anaconda3\lib\site-packages\transformers\pipelines\__init__.py", line 767, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
  File "C:\Users\Main\anaconda3\lib\site-packages\transformers\pipelines\text2text_generation.py", line 47, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Main\anaconda3\lib\site-packages\transformers\pipelines\base.py", line 768, in __init__
    self.device = device if framework == "tf" else torch.device("cpu" if device < 0 else f"cuda:{device}")
TypeError: '<' not supported between instances of 'str' and 'int'

### Versions
Python Version 3.9.12

Pytorch 1.31.1 for Cuda 11.7

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

**Comment by thatDudo** [comment]
Perhaps your pip dependencies are outdated. Run `pip install transformers -U`. To update all packages run `pip install -r requirements.txt -U`.

**Comment by HolzerDavid** [comment]
@thatDudo 
Thank you for your quick reply

I updated the dependencies, now i get this error:

Task state 841d786235f863a5c8130a7e16ebf4a30b1d735ad7ecaec5784a72b0413f5be0-1536-offline-ENG-default-auto to {'info': 'error', 'finished': True}
ERROR: [web] TypeError: _clean_translation_output() missing 1 required positional argument: 'trans'
Traceback (most recent call last):
  File "P:\manga-image-translator\manga_translator\manga_translator.py", line 181, in translate
    return await self._translate(image, params)
  File "P:\manga-image-translator\manga_translator\manga_translator.py", line 243, in _translate
    translated_sentences = await self._run_text_translation(params.translator, 'auto', params.target_lang,
  File "P:\manga-image-translator\manga_translator\manga_translator.py", line 477, in _run_text_translation
    return await super()._run_text_translation(key, src_lang, tgt_lang, text_regions, use_mtpe)
  File "P:\manga-image-translator\manga_translator\manga_translator.py", line 339, in _run_text_translation
    return await dispatch_translation(key, src_lang, tgt_lang, [r.get_text() for r in text_regions], use_mtpe,
  File "P:\manga-image-translator\manga_translator\translators\__init__.py", line 86, in dispatch
    return await translator.translate(src_lang, tgt_lang, queries, use_mtpe)
  File "P:\manga-image-translator\manga_translator\translators\selective.py", line 74, in translate
    return await self._real_translator.translate(from_lang, to_lang, queries, use_mtpe)
  File "P:\manga-image-translator\manga_translator\translators\common.py", line 79, in translate
    result = await self._translate(*self.parse_language_codes(from_lang, to_lang, fatal=True), queries)
  File "P:\manga-image-translator\manga_translator\translators\common.py", line 140, in _translate
    return await self.forward(*args, **kwargs)
  File "P:\manga-image-translator\manga_translator\utils\inference.py", line 329, in forward
    return await self._forward(*args, **kwargs)
  File "P:\manga-image-translator\manga_translator\translators\nllb.py", line 74, in _forward
    return [self._translate_sentence(from_lang, to_lang, query) for query in queries]
  File "P:\manga-image-translator\manga_translator\translators\nllb.py", line 74, in <listcomp>
    return [self._translate_sentence(from_lang, to_lang, query) for query in queries]
  File "P:\manga-image-translator\manga_translator\translators\nllb.py", line 100, in _translate_sentence
    translated_text = self._clean_translation_output(result[0]['translation_text'])
TypeError: _clean_translation_output() missing 1 required positional argument: 'trans'

**Comment by thatDudo** [comment]
I have added a fix. It seems nllb was broken.

**Comment by HolzerDavid** [comment]
thank you so much, it works fine now :)
