### ISSUE TITLE
ERROR: [batch] TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#244]
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 181, in translate
    return await self._translate(image, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 243, in _translate
    translated_sentences = await self._run_text_translation(params.translator, 'auto', params.target_lang,
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 339, in _run_text_translation
    return await dispatch_translation(key, src_lang, tgt_lang, [r.get_text() for r in text_regions], use_mtpe,
  File "F:\manga-image-translator\manga_translator\translators\__init__.py", line 86, in dispatch
    return await translator.translate(src_lang, tgt_lang, queries, use_mtpe)
  File "F:\manga-image-translator\manga_translator\translators\common.py", line 81, in translate
    result = await self._translate(*self.parse_language_codes(from_lang, to_lang, fatal=True), queries)
  File "F:\manga-image-translator\manga_translator\translators\google.py", line 246, in _translate
    lang_to_translation[lang] = (await self._translate_query(from_lang, to_lang, '\n'.join(lang_queries))).text.split('\n')
  File "F:\manga-image-translator\manga_translator\translators\google.py", line 303, in _translate_query
    parsed = json.loads(data[0][2])
  File "F:\1\envs\Mt\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by thatDudo** [comment]
Can you supply the image or the text? Im curious why google returned an empty translation.
