### ISSUE TITLE
ERROR: [web] ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#245]
Traceback (most recent call last):
  File "/content/manga-image-translator/manga_translator/manga_translator.py", line 181, in translate
    return await self._translate(image, params)
  File "/content/manga-image-translator/manga_translator/manga_translator.py", line 259, in _translate
    output = await self._run_text_rendering(params.renderer, img_inpainted, text_regions, params.text_mag_ratio, params.direction,
  File "/content/manga-image-translator/manga_translator/manga_translator.py", line 349, in _run_text_rendering
    output = await dispatch_rendering(img, text_regions, text_mag_ratio, font_path, font_size_offset, font_size_minimum, rearrange_regions, mask)
  File "/content/manga-image-translator/manga_translator/text_rendering/__init__.py", line 301, in dispatch
    img = render(img, region, dst_points, region.alignment, text_mag_ratio, font_size_offset)
  File "/content/manga-image-translator/manga_translator/text_rendering/__init__.py", line 365, in render
    w_ext = int((h * r_orig - w) / 2)
ValueError: cannot convert float NaN to integer
![2023-03-11_13-05-52](https://user-images.githubusercontent.com/49092250/224478263-712b5ef9-82c3-4d7b-b605-df310bb0d349.png)

**Comment by thatDudo** [comment]
I accidentally pushed a local commit that was still in development. I have removed the changes.
