### ISSUE TITLE
--- Logging error ---

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#246]
--- Logging error ---
Traceback (most recent call last):
  File "F:\1\envs\Mt\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "F:\1\envs\Mt\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 25-26: character maps to <undefined>
Call stack:
  File "F:\1\envs\Mt\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\1\envs\Mt\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\manga-image-translator\manga_translator\__main__.py", line 48, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\Mt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "F:\1\envs\Mt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "F:\1\envs\Mt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "F:\1\envs\Mt\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "F:\1\envs\Mt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "F:\manga-image-translator\manga_translator\__main__.py", line 31, in dispatch
    await translator.listen(args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 426, in listen
    await self.translate_path(self._result_path('input.png'), self._result_path('final.png'), params=self._params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 99, in translate_path
    output = await self.translate(Image.open(path), params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 181, in translate
    return await self._translate(image, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 220, in _translate
    text_regions = await self._run_ocr(params.ocr, img_rgb, text_regions)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 442, in _run_ocr
    regions = await super()._run_ocr(key, img, regions)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 326, in _run_ocr
    text_regions = await dispatch_ocr(key, img, text_regions, self.device, self.verbose)
  File "F:\manga-image-translator\manga_translator\ocr\__init__.py", line 33, in dispatch
    return await ocr.recognize(image, regions, verbose)
  File "F:\manga-image-translator\manga_translator\ocr\common.py", line 46, in recognize
    return await self._recognize(image, regions, verbose)
  File "F:\manga-image-translator\manga_translator\ocr\common.py", line 56, in _recognize
    return await self.forward(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\utils\inference.py", line 329, in forward
    return await self._forward(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\ocr\model_48px_ctc.py", line 127, in _forward
    self.logger.info(f'prob: {prob} {txt} fg: ({fr}, {fg}, {fb}) bg: ({br}, {bg}, {bb})')
Message: 'prob: 0.9998685974912914 麗人 fg: (17, 16, 21) bg: (17, 17, 20)'
Arguments: ()
![2023-03-11_14-08-54](https://user-images.githubusercontent.com/49092250/224480856-f0e1ee29-b99b-49dd-b891-754cccac711d.png)
![2023-03-11_14-13-09](https://user-images.githubusercontent.com/49092250/224481050-b847d2d2-3513-4f51-9b8f-6514e67b79b5.png)
#247

**Comment by My12123** [comment]
![608f1226f579e1af9f95e3cdfb42685d](https://user-images.githubusercontent.com/49092250/224480982-27c6d356-fc10-4174-9108-752b9acb4c37.jpeg)

**Comment by thatDudo** [comment]
It should work again. Though english text isnt as well detected as japanese.
![final](https://user-images.githubusercontent.com/58403773/224486401-9470f128-12d3-4fa5-9f5a-d80ff9bae843.png)
