### ISSUE TITLE
--- Logging error ---

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#247]
--- Logging error ---
Traceback (most recent call last):
  File "F:\1\envs\Mt\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "F:\1\envs\Mt\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6-7: character maps to <undefined>
Call stack:
  File "F:\1\envs\Mt\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\1\envs\Mt\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\manga-image-translator\manga_translator\__main__.py", line 48, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\Mt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "F:\1\envs\Mt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "F:\1\envs\Mt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "F:\1\envs\Mt\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "F:\1\envs\Mt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "F:\manga-image-translator\manga_translator\__main__.py", line 31, in dispatch
    await translator.listen(args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 426, in listen
    await self.translate_path(self._result_path('input.png'), self._result_path('final.png'), params=self._params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 99, in translate_path
    output = await self.translate(Image.open(path), params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 181, in translate
    return await self._translate(image, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 259, in _translate
    output = await self._run_text_rendering(params.renderer, img_inpainted, text_regions, params.text_mag_ratio, params.direction,
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 349, in _run_text_rendering
    output = await dispatch_rendering(img, text_regions, text_mag_ratio, font_path, font_size_offset, font_size_minimum, rearrange_regions, mask)
  File "F:\manga-image-translator\manga_translator\text_rendering\__init__.py", line 294, in dispatch
    logger.info(f'text: {region.get_text()}')
Message: 'text: 麗人'
Arguments: ()
![2023-03-11_14-10-11](https://user-images.githubusercontent.com/49092250/224480918-a6be0fd2-3956-4ff4-900f-2a552e7fa687.png)

**Comment by thatDudo** [comment]
Can you show the whole error? The image is missing the bottom part.

**Comment by My12123** [comment]
--- Logging error ---
Traceback (most recent call last):
File "F:\1\envs\Mt\lib\logging_ _.py", line 1103, in emit
stream.write(msg + self.terminator)
File "F:\1\envs\Mt\lib\encodings\cp1251.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6-7: character maps to
Call stack:
File "F:\1\envs\Mt\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "F:\1\envs\Mt\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "F:\manga-image-translator\manga_translator_main.py", line 48, in
loop.run_until_complete(dispatch(args))
File "F:\1\envs\Mt\lib\asyncio\base_events.py", line 636, in run_until_complete
self.run_forever()
File "F:\1\envs\Mt\lib\asyncio\windows_events.py", line 321, in run_forever
super().run_forever()
File "F:\1\envs\Mt\lib\asyncio\base_events.py", line 603, in run_forever
self._run_once()
File "F:\1\envs\Mt\lib\asyncio\base_events.py", line 1899, in _run_once
handle._run()
File "F:\1\envs\Mt\lib\asyncio\events.py", line 80, in _run
self._context.run(self._callback, *self.args)
File "F:\manga-image-translator\manga_translator_ .py", line 31, in dispatch
await translator.listen(args_dict)
File "F:\manga-image-translator\manga_translator\manga_translator.py", line 426, in listen
await self.translate_path(self._result_path('input.png'), self._result_path('final.png'), params=self._params)
File "F:\manga-image-translator\manga_translator\manga_translator.py", line 99, in translate_path
output = await self.translate(Image.open(path), params)
File "F:\manga-image-translator\manga_translator\manga_translator.py", line 181, in translate
return await self._translate(image, params)
File "F:\manga-image-translator\manga_translator\manga_translator.py", line 259, in _translate
output = await self._run_text_rendering(params.renderer, img_inpainted, text_regions, params.text_mag_ratio, params.direction,
File "F:\manga-image-translator\manga_translator\manga_translator.py", line 349, in run_text_rendering
output = await dispatch_rendering(img, text_regions, text_mag_ratio, font_path, font_size_offset, font_size_minimum, rearrange_regions, mask)
File "F:\manga-image-translator\manga_translator\text_rendering_ .py", line 294, in dispatch
logger.info(f'text: {region.get_text()}')
Message: 'text: 麗人'
Arguments: ()

**Comment by thatDudo** [comment]
Ah sorry it seems you had already put the whole exception in your issue. Does the recent commit fix it?

**Comment by My12123** [comment]
@thatDudo 
If there are any more mistakes, I’ll write.
