### ISSUE TITLE
[Bug]: ERROR: [web] FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'result/'

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#311]
### Issue

 FileNotFoundError

### Command Line Arguments

```Shell
python -m manga_translator -v --mode web --use-cuda --font-path=fonts/anime_ace.ttf
```

### Console logs

```Shell
(Mt) F:\manga-image-translator>python -m manga_translator -v --mode web --use-cuda --font-path=fonts/anime_ace.ttf
[web] Running in web mode
Serving up app on http://127.0.0.1:5003

ERROR: [web] FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'result/'
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 64, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\3\envs\Mt\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 41, in dispatch
    await dispatch(args.host, args.port, translation_params=args_dict)
  File "F:\manga-image-translator\manga_translator\server\web_main.py", line 491, in dispatch
    for f in os.listdir('result/'):
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'result/'

(Mt) F:\manga-image-translator>[web_client] Namespace(mode='web_client', input='', dest='', target_lang='CHS', verbose=True, format=None, detector='default', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, translator='google', translator_chain=None, selective_translation=None, use_cuda=True, use_cuda_limited=False, model_dir=None, retries=0, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, font_size=None, font_size_offset=0, font_size_minimum=-1, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, manga2eng=False, chatgpt_prompt_file=None, chatgpt_temperature=0.5, mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', host='127.0.0.1', port=5003, nonce='35b8c0e404e57cd401be655cf0a11bbf', ws_url='ws://localhost:5000', save_quality=100)
[web_client] Running in web_client mode
[web_client] Waiting for translation tasks
ERROR: [web_client] ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5003): Max retries exceeded with url: /connect-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B457492230>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
Traceback (most recent call last):
  File "F:\3\envs\Mt\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "F:\3\envs\Mt\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "F:\3\envs\Mt\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\3\envs\Mt\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "F:\3\envs\Mt\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "F:\3\envs\Mt\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "F:\3\envs\Mt\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "F:\3\envs\Mt\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "F:\3\envs\Mt\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "F:\3\envs\Mt\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "F:\3\envs\Mt\lib\http\client.py", line 975, in send
    self.connect()
  File "F:\3\envs\Mt\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "F:\3\envs\Mt\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001B457492230>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\3\envs\Mt\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "F:\3\envs\Mt\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "F:\3\envs\Mt\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5003): Max retries exceeded with url: /connect-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B457492230>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 64, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\3\envs\Mt\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 45, in dispatch
    await translator.listen(args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 562, in listen
    await self._init_connection()
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 527, in _init_connection
    requests.post(f'http://{self.host}:{self.port}/connect-internal', json=data)
  File "F:\3\envs\Mt\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "F:\3\envs\Mt\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\3\envs\Mt\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\3\envs\Mt\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "F:\3\envs\Mt\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5003): Max retries exceeded with url: /connect-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B457492230>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
```

**Comment by zyddnys** [comment]
try creating `result` folder
