### ISSUE TITLE
[Bug]: ERROR: [batch] InvalidServerResponse: Papago returned invalid response: {'errorCode': 'N2MT09', 'errorMessage': 'language detection failed (언어감지에 실패했습니다.)'}

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#316]
### Issue

InvalidServerResponse

### Command Line Arguments

```Shell
python -m manga_translator -v --mode batch --use-cuda --translator=papago -l RUS --font-path=fonts/anime_ace.ttf -i
```

### Console logs

```Shell
ERROR: [batch] InvalidServerResponse: Papago returned invalid response: {'errorCode': 'N2MT09', 'errorMessage': 'language detection failed (언어감지에 실패했습니다.)'}
Are the API keys set correctly?
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 64, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\3\envs\Mt\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 33, in dispatch
    await translator.translate_path(args.input, dest, args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 146, in translate_path
    await self._translate_file(file_path, output_dest, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 159, in _translate_file
    translation_dict = await self.translate(img, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 235, in translate
    return await self._translate(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 318, in _translate
    ctx.text_regions = await self._run_text_translation(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 453, in _run_text_translation
    translated_sentences = await dispatch_translation(ctx.translator, [region.get_text() for region in ctx.text_regions], ctx.use_mtpe,
  File "F:\manga-image-translator\manga_translator\translators\__init__.py", line 105, in dispatch
    queries = await translator.translate('auto', tgt_lang, queries, use_mtpe)
  File "F:\manga-image-translator\manga_translator\translators\common.py", line 168, in translate
    _translations = await self._translate(*self.parse_language_codes(from_lang, to_lang, fatal=True), queries)
  File "F:\manga-image-translator\manga_translator\translators\papago.py", line 38, in _translate
    raise InvalidServerResponse(f'Papago returned invalid response: {result}\nAre the API keys set correctly?')
manga_translator.translators.common.InvalidServerResponse: Papago returned invalid response: {'errorCode': 'N2MT09', 'errorMessage': 'language detection failed (언어감지에 실패했습니다.)'}
Are the API keys set correctly?
```

**Comment by thatDudo** [comment]
I should probably keep this open for a few days in case someone knows what in particular went wrong.
But i think you mightve not set your api keys correctly as JustFrederik said.

**Comment by JustFrederik** [comment]
@thatDudo i need to correct myself. I didn’t see the title. The problem is that the language isn’t supported. Papago only allows to translate between Chinese and a handful of languages. It’s impossible to translate between  Japanese <=> English.

**Comment by My12123** [comment]
Russian Russian Translation I am translating from English to Russian, and I need to be able to translate from Japanese to Russian at the same time.

**Comment by JustFrederik** [comment]
I’m sorry I mixed up the youdao and papgo translator. What I said before was wrong😅. I tried it with my web scraper and it worked. I go back to my first statement that it is probably the api key. I don’t have a key so I can’t test it
