### ISSUE TITLE
AttributeError: 'Point' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by AiYouWei** [zyddnys/manga-image-translator#335]
### Issue

  polys[i] = np.roll(np.asarray(list(rect.exterior.coords)[:4]), 2)
AttributeError: 'Point' object has no attribute 'exterior'

### Command Line Arguments

```Shell
python  -m manga_translator --verbose --mode batch --use-cuda --det-auto-rotate --det-gamma-correct --translator=m2m100 --detector=craft --target-lang=KOR -f=jpg -i
```

### Console logs

```Shell
ERROR: [batch] AttributeError: 'Point' object has no attribute 'exterior'
Traceback (most recent call last):
  File "D:\StudioProjects\manga-image-translator\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "D:\ProgramData\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\StudioProjects\manga-image-translator\manga_translator\__main__.py", line 35, in dispatch
    await translator.translate_path(args.input, dest, args_dict)
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 149, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 167, in _translate_file
    translation_dict = await self.translate(img, params)
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 240, in translate
    return await self._translate(ctx)
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 306, in _translate
    ctx.text_regions, ctx.mask_raw, ctx.mask = await self._run_detection(ctx)
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 436, in _run_detection
    return await dispatch_detection(ctx.detector, ctx.img_rgb, ctx.detection_size, ctx.text_threshold, ctx.box_threshold,
  File "D:\StudioProjects\manga-image-translator\manga_translator\detection\__init__.py", line 35, in dispatch
    return await detector.detect(image, detect_size, text_threshold, box_threshold, unclip_ratio, invert, gamma_correct, rotate, auto_rotate, verbose)
  File "D:\StudioProjects\manga-image-translator\manga_translator\detection\common.py", line 47, in detect
    text_regions, raw_mask, mask = await self._detect(image, detect_size, text_threshold, box_threshold, unclip_ratio, verbose)
  File "D:\StudioProjects\manga-image-translator\manga_translator\detection\common.py", line 165, in _detect
    return await self.infer(*args, **kwargs)
  File "D:\StudioProjects\manga-image-translator\manga_translator\utils\inference.py", line 329, in infer
    return await self._infer(*args, **kwargs)
  File "D:\StudioProjects\manga-image-translator\manga_translator\detection\craft.py", line 190, in _infer
    polys[i] = np.roll(np.asarray(list(rect.exterior.coords)[:4]), 2)
AttributeError: 'Point' object has no attribute 'exterior'
```

**Comment by zyddnys** [comment]
which version of shapely do you have? you can check by running `pip show shapely`

**Comment by AiYouWei** [comment]
WARNING: Ignoring invalid distribution -orch (d:\programdata\anaconda3\lib\site-packages)
Name: shapely
Version: 2.0.1
Summary: Manipulation and analysis of geometric objects
Home-page:
Author: Sean Gillies
Author-email:
License: BSD 3-Clause
Location: d:\programdata\anaconda3\lib\site-packages
Requires: numpy
Required-by:
PS D:\StudioProjects\manga-image-translator>

**Comment by zyddnys** [comment]
i was unable to reproduce this error, can you share the exact image that triggered this error?

**Comment by AiYouWei** [comment]
![129ea6fd06d67e09dec30e25](https://user-images.githubusercontent.com/6127240/236575159-e9d43200-eb54-496c-a877-1c5ebd845dfa.jpg)
