### ISSUE TITLE
[batch] error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:3298: error: (-215:Assertion failed) (M0.type() == CV_32F || M0.type() == CV_64F) && M0.rows == 3 && M0.cols == 3 in function 'cv::warpPerspe ctive'[Bug]: 

### ISSUE THREAD

**Issue by AiYouWei** [zyddnys/manga-image-translator#337]
### Issue

[batch] error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:3298: error: (-215:Assertion failed) (M0.type() == CV_32F || M0.type() == CV_64F) && M0.rows == 3 && M0.cols == 3 in function 'cv::warpPerspe
ctive'
![c64f16dd2c84ee45208067cc](https://user-images.githubusercontent.com/6127240/236716489-899e3337-da13-4850-a9b9-31a3bae1bbe1.jpg)

### Command Line Arguments

```Shell
python  -m manga_translator --verbose --mode batch --use-cuda --translator=m2m100 --det-gamma-correct --det-auto-rotate --detector=default --retries=10 --filter-text='.*送.*' --target-lang=KOR -f=jpg
```

### Console logs

```Shell
ERROR: [batch] error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:3298: error: (-215:Assertion failed) (M0.type() == CV_32F || M0.type() == CV_64F) && M0.rows == 3 && M0.cols == 3 in function 'cv::warpPerspe
ctive'
Traceback (most recent call last):
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 242, in translate
    return await self._translate(ctx)
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 319, in _translate
    ctx.text_regions = await self._run_ocr(ctx)
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 443, in _run_ocr
  File "D:\StudioProjects\manga-image-translator\manga_translator\ocr\__init__.py", line 33, in dispatch
    return await ocr.recognize(image, regions, verbose)
  File "D:\StudioProjects\manga-image-translator\manga_translator\ocr\common.py", line 46, in recognize
    return await self._recognize(image, regions, verbose)
  File "D:\StudioProjects\manga-image-translator\manga_translator\ocr\common.py", line 56, in _recognize
    return await self.infer(*args, **kwargs)
  File "D:\StudioProjects\manga-image-translator\manga_translator\utils\inference.py", line 329, in infer
    return await self._infer(*args, **kwargs)
  File "D:\StudioProjects\manga-image-translator\manga_translator\ocr\model_48px_ctc.py", line 60, in _infer
    region_imgs = [q.get_transformed_region(image, d, text_height) for q, d in quadrilaterals]
  File "D:\StudioProjects\manga-image-translator\manga_translator\ocr\model_48px_ctc.py", line 60, in <listcomp>
    region_imgs = [q.get_transformed_region(image, d, text_height) for q, d in quadrilaterals]
  File "D:\StudioProjects\manga-image-translator\manga_translator\utils\textblock.py", line 218, in get_transformed_region
    region = cv2.warpPerspective(img, M, (w, h))
```

**Comment by 1439707509** [comment]
这个是专门给漫画用的，你用真人图片干吗？
