### ISSUE TITLE
我想问一下一翻译就报错怎么办

### ISSUE THREAD

**Issue by PROBEFISH** [zyddnys/manga-image-translator#338]
TypeError: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "C:\Users\shi20\AppData\Local\Programs\Python\Python310\Lib\site-packages\manga-image-translator-main\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "C:\Users\shi20\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\shi20\AppData\Local\Programs\Python\Python310\Lib\site-packages\manga-image-translator-main\manga_translator\__main__.py", line 47, in dispatch
    await translator.listen(args_dict)
  File "C:\Users\shi20\AppData\Local\Programs\Python\Python310\Lib\site-packages\manga-image-translator-main\manga_translator\manga_translator.py", line 592, in listen
    await self.translate_path(self._result_path('input.jpg'), self._result_path('final.'+self._params.get('format','jpg')), params=self._params)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by gomingge** [comment]
我也遇到这个问题了,colab部署的,请问你解决了没

**Comment by gomingge** [comment]
这个是因为format路径错误导致的, 我下面截图就是改动点, 或者你拉取我的分支https://github.com/gomingge/manga-image-translator
![image](https://user-images.githubusercontent.com/23419138/237042345-633c1aaa-05cf-45a1-9cac-de5e5afcbefc.png)
