### ISSUE TITLE
[Bug]: attribute error when using gpt3

### ISSUE THREAD

**Issue by buriburix5** [zyddnys/manga-image-translator#339]
### Issue

Im having this error when trying to use gpt3. Also gpt3.5 worked well but got ratelimiting after few pages...

### Command Line Arguments

```Shell
python -m manga_translator --use-cuda --v --mode batch --translator=gpt3 -l ENG -i D:\Images\Test2\
```

### Console logs

```Shell
ERROR: [batch] AttributeError: 'str' object has no attribute 'usage'
Traceback (most recent call last):
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "C:\ProgramData\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\__main__.py", line 35, in dispatch
    await translator.translate_path(args.input, dest, args_dict)
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\manga_translator.py", line 149, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\manga_translator.py", line 169, in _translate_file
    translation_dict = await self.translate(img, params)
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\manga_translator.py", line 242, in translate
    return await self._translate(ctx)
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\manga_translator.py", line 325, in _translate
    ctx.text_regions = await self._run_text_translation(ctx)
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\manga_translator.py", line 460, in _run_text_translation
    translated_sentences = await dispatch_translation(ctx.translator, [region.get_text() for region in ctx.text_regions], ctx.use_mtpe,
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\translators\__init__.py", line 105, in dispatch
    queries = await translator.translate('auto', tgt_lang, queries, use_mtpe)
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\translators\common.py", line 168, in translate
    _translations = await self._translate(*self.parse_language_codes(from_lang, to_lang, fatal=True), queries)
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\translators\chatgpt.py", line 116, in _translate
    response = await request_task
  File "C:\Users\DIEU PHI\manga-image-translator\manga_translator\translators\chatgpt.py", line 142, in _request_translation
    self.token_count += response.usage['total_tokens']
AttributeError: 'str' object has no attribute 'usage'
```

**Comment by 1439707509** [comment]
那你别用gpt3，或者等美国人都睡觉的时候，才用好了

**Comment by thatDudo** [comment]
Sorry it seems i mixed up some variables
