### ISSUE TITLE
[Bug]: ERROR: [web_client] TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#347]
### Issue

ERROR

### Command Line Arguments

```Shell
python -m manga_translator -v --mode web --use-cuda --font-path=fonts/anime_ace.ttf
```

### Console logs

```Shell
(manga-image-translator) F:\manga-image-translator>python -m manga_translator -v --mode web --use-cuda --font-path=fonts/anime_ace.ttf
[web] Running in web mode
Serving up app on http://127.0.0.1:5003

[web_client] Namespace(mode='web_client', input='', dest='', target_lang='CHS', verbose=True, format=None, detector='default', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, translator='google', translator_chain=None, selective_translation=None, use_cuda=True, use_cuda_limited=False, model_dir=None, retries=0, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, font_size=None, font_size_offset=0, font_size_minimum=-1, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, manga2eng=False, chatgpt_prompt_file=None, chatgpt_temperature=0.3, mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', host='127.0.0.1', port=5003, nonce='f5fb0acc2c3cc9fdf12b0c34216ae498', ws_url='ws://localhost:5000', save_quality=100)
[web_client] Running in web_client mode
[web_client] Waiting for translation tasks
New `submit` task 903f707b6f402fe8bcad8b91b2f0d60e717a0e0f2b5b63be74461e181981f076-1536-google-RUS-default-auto
[web_client] Processing task 903f707b6f402fe8bcad8b91b2f0d60e717a0e0f2b5b63be74461e181981f076-1536-google-RUS-default-auto
ERROR: [web_client] TypeError: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 47, in dispatch
    await translator.listen(args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 592, in listen
    await self.translate_path(self._result_path('input.jpg'), self._result_path('final.'+self._params.get('format','jpg')), params=self._params)
TypeError: can only concatenate str (not "NoneType") to str
Restarting translator process
[web_client] Namespace(mode='web_client', input='', dest='', target_lang='CHS', verbose=True, format=None, detector='default', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, translator='google', translator_chain=None, selective_translation=None, use_cuda=True, use_cuda_limited=False, model_dir=None, retries=0, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, font_size=None, font_size_offset=0, font_size_minimum=-1, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, manga2eng=False, chatgpt_prompt_file=None, chatgpt_temperature=0.3, mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', host='127.0.0.1', port=5003, nonce='f5fb0acc2c3cc9fdf12b0c34216ae498', ws_url='ws://localhost:5000', save_quality=100)
New `submit` task e8a7636c8d3394cbca2cca309cdb18f49987b5b2938d39b593ac5e3ac3742c19-1536-google-RUS-default-auto
[web_client] Running in web_client mode
[web_client] Waiting for translation tasks
[web_client] Processing task e8a7636c8d3394cbca2cca309cdb18f49987b5b2938d39b593ac5e3ac3742c19-1536-google-RUS-default-auto
ERROR: [web_client] TypeError: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 47, in dispatch
    await translator.listen(args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 592, in listen
    await self.translate_path(self._result_path('input.jpg'), self._result_path('final.'+self._params.get('format','jpg')), params=self._params)
TypeError: can only concatenate str (not "NoneType") to str
Restarting translator process
[web_client] Namespace(mode='web_client', input='', dest='', target_lang='CHS', verbose=True, format=None, detector='default', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, translator='google', translator_chain=None, selective_translation=None, use_cuda=True, use_cuda_limited=False, model_dir=None, retries=0, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, font_size=None, font_size_offset=0, font_size_minimum=-1, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, manga2eng=False, chatgpt_prompt_file=None, chatgpt_temperature=0.3, mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', host='127.0.0.1', port=5003, nonce='f5fb0acc2c3cc9fdf12b0c34216ae498', ws_url='ws://localhost:5000', save_quality=100)
[web_client] Running in web_client mode
[web_client] Waiting for translation tasks
New `submit` task ebae195d92a635de089e9ccf5a9f33240dc535a63360b427d06de195b30e8ccc-1536-google-RUS-default-auto
[web_client] Processing task ebae195d92a635de089e9ccf5a9f33240dc535a63360b427d06de195b30e8ccc-1536-google-RUS-default-auto
ERROR: [web_client] TypeError: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 47, in dispatch
    await translator.listen(args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 592, in listen
    await self.translate_path(self._result_path('input.jpg'), self._result_path('final.'+self._params.get('format','jpg')), params=self._params)
TypeError: can only concatenate str (not "NoneType") to str
Restarting translator process
[web_client] Namespace(mode='web_client', input='', dest='', target_lang='CHS', verbose=True, format=None, detector='default', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, translator='google', translator_chain=None, selective_translation=None, use_cuda=True, use_cuda_limited=False, model_dir=None, retries=0, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, font_size=None, font_size_offset=0, font_size_minimum=-1, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, manga2eng=False, chatgpt_prompt_file=None, chatgpt_temperature=0.3, mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', host='127.0.0.1', port=5003, nonce='f5fb0acc2c3cc9fdf12b0c34216ae498', ws_url='ws://localhost:5000', save_quality=100)
[web_client] Running in web_client mode
[web_client] Waiting for translation tasks
```

**Comment by gomingge** [comment]
改动这里就好了,我的分支https://github.com/gomingge/manga-image-translator
![image](https://user-images.githubusercontent.com/23419138/237042197-42d09e01-31d0-47bf-a988-3fbaec144527.png)
