### ISSUE TITLE
[Bug]: craft detector throws errors

### ISSUE THREAD

**Issue by fastgar** [zyddnys/manga-image-translator#369]
### Issue

Hi,

today i tried the craft detector, but regardless which manga i try it on i always get the following error:

ERROR: [batch] ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48,) + inhomogeneous part.

OS: Windows 10
Python Version: 3.10.8

I am up to date with github
D:\workspace\manga-image-translator>git pull
Already up to date.

### Command Line Arguments

```Shell
run.bat -m batch -i "D:\Manga\Choir!\Choir! 001" -o D:\choir_test_craft -l JPN --detector craft --translator sugoi --use-cuda --save-text --verbose
```

### Console logs

```Shell
[batch] Namespace(mode='batch', input='D:\\Manga\\Choir!\\Choir! 001', dest='D:\\choir_test_craft', target_lang='JPN', verbose=True, format=None, detector='craft', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, colorizer=None, translator='sugoi', translator_chain=None, selective_translation=None, use_cuda=True, use_cuda_limited=False, model_dir=None, retries=0, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, inpainting_size=2048, colorization_size=1024, font_size=None, font_size_offset=0, font_size_minimum=-1, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, manga2eng=False, chatgpt_prompt_file=None, chatgpt_temperature=0.3, mtpe=False, save_text=True, save_text_file='', filter_text=None, prep_manual=False, font_path='', host='127.0.0.1', port=5003, nonce='', ws_url='ws://localhost:5000', save_quality=100)
[batch] Running in batch mode
[batch] Translating: D:\Manga\Choir!\Choir! 001\001.jpg -> D:\choir_test_craft\001.png
[batch] Loading models
[batch] Running text detection
ERROR: [batch] ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48,) + inhomogeneous part.
Traceback (most recent call last):
  File "D:\workspace\manga-image-translator\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\workspace\manga-image-translator\manga_translator\__main__.py", line 35, in dispatch
    await translator.translate_path(args.input, dest, args_dict)
  File "D:\workspace\manga-image-translator\manga_translator\manga_translator.py", line 154, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "D:\workspace\manga-image-translator\manga_translator\manga_translator.py", line 173, in _translate_file
    translation_dict = await self.translate(img, params)
  File "D:\workspace\manga-image-translator\manga_translator\manga_translator.py", line 249, in translate
    return await self._translate(ctx)
  File "D:\workspace\manga-image-translator\manga_translator\manga_translator.py", line 321, in _translate
    ctx.text_regions, ctx.mask_raw, ctx.mask = await self._run_detection(ctx)
  File "D:\workspace\manga-image-translator\manga_translator\manga_translator.py", line 455, in _run_detection
    return await dispatch_detection(ctx.detector, ctx.img_rgb, ctx.detection_size, ctx.text_threshold, ctx.box_threshold,
  File "D:\workspace\manga-image-translator\manga_translator\detection\__init__.py", line 35, in dispatch
    return await detector.detect(image, detect_size, text_threshold, box_threshold, unclip_ratio, invert, gamma_correct, rotate, auto_rotate, verbose)
  File "D:\workspace\manga-image-translator\manga_translator\detection\common.py", line 47, in detect
    text_regions, raw_mask, mask = await self._detect(image, detect_size, text_threshold, box_threshold, unclip_ratio, verbose)
  File "D:\workspace\manga-image-translator\manga_translator\detection\common.py", line 172, in _detect
    return await self.infer(*args, **kwargs)
  File "D:\workspace\manga-image-translator\manga_translator\utils\inference.py", line 329, in infer
    return await self._infer(*args, **kwargs)
  File "D:\workspace\manga-image-translator\manga_translator\detection\craft.py", line 177, in _infer
    polys = craft_utils.adjustResultCoordinates(polys, ratio_w, ratio_h)
  File "D:\workspace\manga-image-translator\manga_translator\detection\default_utils\craft_utils.py", line 240, in adjustResultCoordinates
    polys = np.array(polys)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48,) + inhomogeneous part.
```

**Comment by zyddnys** [comment]
can you provide the exact image that caused this issue?

**Comment by fastgar** [comment]
I tried craft with 15 manga's and it errors out on the first image of everyone.

A quick note somewhere regarding not using craft for manga would be good.

Here one of the images that fail.
![another_kiss_ch09_141](https://github.com/zyddnys/manga-image-translator/assets/12036024/2326240b-af19-41be-b639-c2d0028a0983)
