### ISSUE TITLE
[Bug]: ERROR: [batch] ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#371]
### Issue

ERROR: [batch] ValueError: setting an array element with a sequence.

### Command Line Arguments

```Shell
python -m manga_translator -v --mode batch --use-cuda --translator=papago -l RUS --font-path=fonts/anime_ace.ttf --detector craft -i
```

### Console logs

```Shell
(manga-image-translator) F:\manga-image-translator>python -m manga_translator -v --mode batch --use-cuda --translator=papago -l RUS --font-path=fonts/anime_ace.ttf --detector craft -i "I:\The Demon of Your Dreams\Chapter 1_ Chapter 1"
[batch] Namespace(mode='batch', input='I:\\The Demon of Your Dreams\\Chapter 1_ Chapter 1', dest='', target_lang='RUS', verbose=True, format=None, detector='craft', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, colorizer=None, translator='papago', translator_chain=None, selective_translation=None, use_cuda=True, use_cuda_limited=False, model_dir=None, retries=0, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, inpainting_size=2048, colorization_size=1024, font_size=None, font_size_offset=0, font_size_minimum=-1, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, manga2eng=False, chatgpt_prompt_file=None, chatgpt_temperature=0.3, mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='fonts/anime_ace.ttf', host='127.0.0.1', port=5003, nonce='', ws_url='ws://localhost:5000', save_quality=100)
[batch] Running in batch mode
[batch] Translating: I:\The Demon of Your Dreams\Chapter 1_ Chapter 1\001.jpg -> I:\The Demon of Your Dreams\Chapter 1_ Chapter 1-translated\001.png
[batch] Loading models

Downloading models into F:\manga-image-translator\models\detection

 -- Downloading: "https://github.com/zyddnys/manga-image-translator/releases/download/beta-0.3/craft_refiner_CTW1500.pth"
craft_refiner_CTW1500.pth.part: 100%|████████████████████████████████████████████| 1.77M/1.77M [00:00<00:00, 3.02MiB/s]
 -- Verifying: "F:\manga-image-translator\models\detection\craft_refiner_CTW1500.pth.part"
 -- Verifying: OK!

 -- Downloading: "https://github.com/zyddnys/manga-image-translator/releases/download/beta-0.3/craft_mlt_25k.pth"
craft_mlt_25k.pth.part: 100%|████████████████████████████████████████████████████| 79.3M/79.3M [00:15<00:00, 5.50MiB/s]
 -- Verifying: "F:\manga-image-translator\models\detection\craft_mlt_25k.pth.part"
 -- Verifying: OK!

[batch] Running text detection
ERROR: [batch] ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (39,) + inhomogeneous part.
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 35, in dispatch
    await translator.translate_path(args.input, dest, args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 154, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 173, in _translate_file
    translation_dict = await self.translate(img, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 249, in translate
    return await self._translate(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 321, in _translate
    ctx.text_regions, ctx.mask_raw, ctx.mask = await self._run_detection(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 455, in _run_detection
    return await dispatch_detection(ctx.detector, ctx.img_rgb, ctx.detection_size, ctx.text_threshold, ctx.box_threshold,
  File "F:\manga-image-translator\manga_translator\detection\__init__.py", line 37, in dispatch
    return await detector.detect(image, detect_size, text_threshold, box_threshold, unclip_ratio, invert, gamma_correct, rotate, auto_rotate, verbose)
  File "F:\manga-image-translator\manga_translator\detection\common.py", line 47, in detect
    text_regions, raw_mask, mask = await self._detect(image, detect_size, text_threshold, box_threshold, unclip_ratio, verbose)
  File "F:\manga-image-translator\manga_translator\detection\common.py", line 172, in _detect
    return await self.infer(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\utils\inference.py", line 329, in infer
    return await self._infer(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\detection\craft.py", line 177, in _infer
    polys = craft_utils.adjustResultCoordinates(polys, ratio_w, ratio_h)
  File "F:\manga-image-translator\manga_translator\detection\default_utils\craft_utils.py", line 240, in adjustResultCoordinates
    polys = np.array(polys)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (39,) + inhomogeneous part.
```

**Comment by zyddnys** [comment]
can you provide the exact image that caused this issue?

**Comment by My12123** [comment]
![001](https://github.com/zyddnys/manga-image-translator/assets/49092250/c7d88aca-ea52-4148-8fb5-7ebb55af3443)

**Comment by My12123** [comment]
```python
(manga-image-translator) F:\manga-image-translator>python -m manga_translator -v --mode batch --use-cuda --translator=papago -l RUS --font-path=fonts/anime_ace.ttf --detector craft -i "I:\The Demon of Your Dreams\Chapter 2_ Chapter 2"
[batch] Namespace(mode='batch', input='I:\\The Demon of Your Dreams\\Chapter 2_ Chapter 2', dest='', target_lang='RUS', verbose=True, format=None, detector='craft', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, colorizer=None, translator='papago', translator_chain=None, selective_translation=None, use_cuda=True, use_cuda_limited=False, model_dir=None, retries=0, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, inpainting_size=2048, colorization_size=1024, font_size=None, font_size_offset=0, font_size_minimum=-1, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, manga2eng=False, chatgpt_prompt_file=None, chatgpt_temperature=0.3, mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='fonts/anime_ace.ttf', host='127.0.0.1', port=5003, nonce='', ws_url='ws://localhost:5000', save_quality=100)
[batch] Running in batch mode
[batch] Translating: I:\The Demon of Your Dreams\Chapter 2_ Chapter 2\001.jpg -> I:\The Demon of Your Dreams\Chapter 2_ Chapter 2-translated\001.png
[batch] Loading models
[batch] Running text detection
ERROR: [batch] ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (24,) + inhomogeneous part.
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 35, in dispatch
    await translator.translate_path(args.input, dest, args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 154, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 173, in _translate_file
    translation_dict = await self.translate(img, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 249, in translate
    return await self._translate(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 321, in _translate
    ctx.text_regions, ctx.mask_raw, ctx.mask = await self._run_detection(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 455, in _run_detection
    return await dispatch_detection(ctx.detector, ctx.img_rgb, ctx.detection_size, ctx.text_threshold, ctx.box_threshold,
  File "F:\manga-image-translator\manga_translator\detection\__init__.py", line 37, in dispatch
    return await detector.detect(image, detect_size, text_threshold, box_threshold, unclip_ratio, invert, gamma_correct, rotate, auto_rotate, verbose)
  File "F:\manga-image-translator\manga_translator\detection\common.py", line 47, in detect
    text_regions, raw_mask, mask = await self._detect(image, detect_size, text_threshold, box_threshold, unclip_ratio, verbose)
  File "F:\manga-image-translator\manga_translator\detection\common.py", line 172, in _detect
    return await self.infer(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\utils\inference.py", line 329, in infer
    return await self._infer(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\detection\craft.py", line 177, in _infer
    polys = craft_utils.adjustResultCoordinates(polys, ratio_w, ratio_h)
  File "F:\manga-image-translator\manga_translator\detection\default_utils\craft_utils.py", line 240, in adjustResultCoordinates
    polys = np.array(polys)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (24,) + inhomogeneous part.
``` 
![001](https://github.com/zyddnys/manga-image-translator/assets/49092250/16a8dd1b-1ed7-4358-943f-7e0d80b85bc6)

**Comment by zyddnys** [comment]
no luck reproducing this error
```
[demo] Translating: [redacted]\239707234-c7d88aca-ea52-4148-8fb5-7ebb55af3443.jpg -> [redacted]\result\final.png
[demo] Loading models
[demo] Running text detection
WARNING: [demo] No text regions! - Skipping
[demo] Saving results
```

**Comment by My12123** [comment]
What is CRAFT detector used for?

**Comment by zyddnys** [comment]
still unable to reproduce, craft is used for translating things like receipts, not manga, just don't use craft should solve the issue
