### ISSUE TITLE
[Bug]: ERROR: [batch] OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#373]
### Issue

OutOfMemoryError: CUDA out of memory.

### Command Line Arguments

```Shell
python -m manga_translator -v --mode batch --use-cuda --colorizer mc2 --detector none -i
```

### Console logs

```Shell
(manga-image-translator) F:\manga-image-translator>python -m manga_translator -v --mode batch --use-cuda --colorizer mc2 --detector none -i F:\manga_grabber_v2.1.6_win_x64\manga\neromantichnyi__A35c96\vol1\1
[batch] Namespace(mode='batch', input='F:\\manga_grabber_v2.1.6_win_x64\\manga\\neromantichnyi__A35c96\\vol1\\1', dest='', target_lang='CHS', verbose=True, format=None, detector='none', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, colorizer='mc2', translator='google', translator_chain=None, selective_translation=None, use_cuda=True, use_cuda_limited=False, model_dir=None, retries=0, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, inpainting_size=2048, colorization_size=1024, font_size=None, font_size_offset=0, font_size_minimum=-1, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, manga2eng=False, chatgpt_prompt_file=None, chatgpt_temperature=0.3, mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', host='127.0.0.1', port=5003, nonce='', ws_url='ws://localhost:5000', save_quality=100)
[batch] Running in batch mode
[batch] Translating: F:\manga_grabber_v2.1.6_win_x64\manga\neromantichnyi__A35c96\vol1\1\000.png_res.jpg -> F:\manga_grabber_v2.1.6_win_x64\manga\neromantichnyi__A35c96\vol1\1-translated\000.png_res.png
[batch] Loading models
[batch] Running colorization
[batch] Running text detection
WARNING: [batch] No text regions! - Skipping
[batch] Saving results
[batch] Translating: F:\manga_grabber_v2.1.6_win_x64\manga\neromantichnyi__A35c96\vol1\1\001.png -> F:\manga_grabber_v2.1.6_win_x64\manga\neromantichnyi__A35c96\vol1\1-translated\001.png
[batch] Loading models
[batch] Running colorization
ERROR: [batch] OutOfMemoryError: CUDA out of memory. Tried to allocate 1.65 GiB (GPU 0; 8.00 GiB total capacity; 5.25 GiB already allocated; 0 bytes free; 5.85 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 35, in dispatch
    await translator.translate_path(args.input, dest, args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 154, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 173, in _translate_file
    translation_dict = await self.translate(img, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 249, in translate
    return await self._translate(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 306, in _translate
    ctx.img_colorized = await self._run_colorizer(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 449, in _run_colorizer
    return await dispatch_colorization(ctx.colorizer, ctx.input, ctx.colorization_size, self.device)
  File "F:\manga-image-translator\manga_translator\colorization\__init__.py", line 28, in dispatch
    return await colorizer.colorize(image, colorization_size)
  File "F:\manga-image-translator\manga_translator\colorization\common.py", line 10, in colorize
    return await self._colorize(image, colorization_size)
  File "F:\manga-image-translator\manga_translator\colorization\common.py", line 20, in _colorize
    return await self.infer(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\utils\inference.py", line 329, in infer
    return await self._infer(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\colorization\manga_colorization_v2.py", line 60, in _infer
    fake_color, _ = self.colorizer(torch.cat([current_image, current_hint], 1))
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\colorization\manga_colorization_v2_utils\networks\models.py", line 318, in forward
    fake, guide = self.generator(x)
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\colorization\manga_colorization_v2_utils\networks\models.py", line 293, in forward
    x1, x2, x3, x4 = self.encoder(sketch[:, 0:1])
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\colorization\manga_colorization_v2_utils\networks\extractor.py", line 121, in forward
    x2 = self.layer1(x1)
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\manga-image-translator\manga_translator\colorization\manga_colorization_v2_utils\networks\extractor.py", line 65, in forward
    residual = self.downsample(x)
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\modules\batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "F:\1\envs\manga-image-translator\lib\site-packages\torch\nn\functional.py", line 2450, in batch_norm
    return torch.batch_norm(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.65 GiB (GPU 0; 8.00 GiB total capacity; 5.25 GiB already allocated; 0 bytes free; 5.85 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
![001](https://github.com/zyddnys/manga-image-translator/assets/49092250/613d9476-b21e-44df-9320-67abf78b7b1e)
Is it possible to add an automatic separation function?

**Comment by My12123** [comment]
```python
[batch] Running colorization
ERROR: [batch] OutOfMemoryError: CUDA out of memory. Tried to allocate 1.25 GiB (GPU 0; 14.75 GiB total capacity; 10.21 GiB already allocated; 426.81 MiB free; 13.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/content/manga-image-translator/manga_translator/__main__.py", line 74, in <module>
    loop.run_until_complete(dispatch(args))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/content/manga-image-translator/manga_translator/__main__.py", line 43, in dispatch
    await translator.translate_path(path, dest, args_dict)
  File "/content/manga-image-translator/manga_translator/manga_translator.py", line 157, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "/content/manga-image-translator/manga_translator/manga_translator.py", line 179, in _translate_file
    translation_dict = await self.translate(img, params)
  File "/content/manga-image-translator/manga_translator/manga_translator.py", line 253, in translate
    return await self._translate(ctx)
  File "/content/manga-image-translator/manga_translator/manga_translator.py", line 310, in _translate
    ctx.img_colorized = await self._run_colorizer(ctx)
  File "/content/manga-image-translator/manga_translator/manga_translator.py", line 387, in _run_colorizer
    return await dispatch_colorization(ctx.colorizer, ctx.input, ctx.colorization_size, self.device)
  File "/content/manga-image-translator/manga_translator/colorization/__init__.py", line 28, in dispatch
    return await colorizer.colorize(image, colorization_size)
  File "/content/manga-image-translator/manga_translator/colorization/common.py", line 10, in colorize
    return await self._colorize(image, colorization_size)
  File "/content/manga-image-translator/manga_translator/colorization/common.py", line 20, in _colorize
    return await self.infer(*args, **kwargs)
  File "/content/manga-image-translator/manga_translator/utils/inference.py", line 329, in infer
    return await self._infer(*args, **kwargs)
  File "/content/manga-image-translator/manga_translator/colorization/manga_colorization_v2.py", line 60, in _infer
    fake_color, _ = self.colorizer(torch.cat([current_image, current_hint], 1))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/manga-image-translator/manga_translator/colorization/manga_colorization_v2_utils/networks/models.py", line 318, in forward
    fake, guide = self.generator(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/manga-image-translator/manga_translator/colorization/manga_colorization_v2_utils/networks/models.py", line 299, in forward
    x = self.tunnel3(torch.cat([out, x3], 1))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.25 GiB (GPU 0; 14.75 GiB total capacity; 10.21 GiB already allocated; 426.81 MiB free; 13.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
