### ISSUE TITLE
[Bug]: ERROR: [batch] ConnectTimeout: HTTPSConnectionPool(host='papago.naver.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000273BFCA4670>, 'Connection to papago.

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#389]
### Issue

requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='papago.naver.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000273BFCA4670>, 'Connection to papago.naver.com timed out. (connect timeout=None)'))

### Command Line Arguments

```Shell
python -m manga_translator -v --mode batch --use-cuda --translator=papago -l RUS --font-path=fonts/anime_ace.ttf --colorizer mc2 -i
```

### Console logs

```Shell
(manga-image-translator) F:\manga-image-translator>python -m manga_translator -v --mode batch --use-cuda --translator=papago -l RUS --font-path=fonts/anime_ace.ttf --colorizer mc2 -i "I:\With a strong-willed Marchioness, Prince Yandere's\Volume 2 Chapter 10"
[batch] Namespace(mode='batch', input="I:\\With a strong-willed Marchioness, Prince Yandere's\\Volume 2 Chapter 10", dest='', target_lang='RUS', verbose=True, format=None, detector='default', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, colorizer='mc2', translator='papago', translator_chain=None, selective_translation=None, use_cuda=True, use_cuda_limited=False, model_dir=None, retries=0, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, inpainting_size=2048, colorization_size=1024, font_size=None, font_size_offset=0, font_size_minimum=-1, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, manga2eng=False, chatgpt_prompt_file=None, chatgpt_temperature=0.3, mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='fonts/anime_ace.ttf', host='127.0.0.1', port=5003, nonce='', ws_url='ws://localhost:5000', save_quality=100)
[batch] Running in batch mode
[batch] Translating: I:\With a strong-willed Marchioness, Prince Yandere's\Volume 2 Chapter 10\001.webp -> I:\With a strong-willed Marchioness, Prince Yandere's\Volume 2 Chapter 10-translated\001.png
[batch] Loading models
[batch] Running colorization
[batch] Running text detection
[DefaultDetector] Detection resolution: 1280x1536
[batch] Running ocr
[Model48pxCTCOCR] prob: 0.7202760040203156 コﾋックス fg: (156, 103, 72) bg: (159, 107, 72)
[Model48pxCTCOCR] prob: 0.8739079161739757 続々重版出来！ fg: (170, 128, 79) bg: (170, 130, 79)
[Model48pxCTCOCR] prob: 0.9946584490075099 待望の第2巻は fg: (171, 134, 85) bg: (171, 136, 85)
[Model48pxCTCOCR] prob: 0.8728095146056661 6月308()発売予定 fg: (153, 121, 82) bg: (155, 122, 81)
[Model48pxCTCOCR] prob: 0.7914073675584321 Ｄ原作小説①〜②着は fg: (86, 63, 73) bg: (86, 64, 72)
[Model48pxCTCOCR] prob: 0.7638070150971765 「還社メリッサ」より大好評発売中！ fg: (45, 27, 41) bg: (45, 25, 38)
[Model48pxCTCOCR] prob: 0.9993481570239972 どうせ fg: (210, 156, 48) bg: (212, 159, 49)
[Model48pxCTCOCR] prob: 0.9924993229782527 セレン fg: (82, 14, 6) bg: (106, 37, 9)
[Model48pxCTCOCR] prob: 0.657073347717468 キャラクター此ミ すらだまみ fg: (99, 67, 45) bg: (105, 71, 46)
[Model48pxCTCOCR] prob: 0.9512520219214735 第10話 fg: (32, 3, 1) bg: (40, 3, 1)
[batch] Running text translation
[PapagoTranslator] Translating into Russian
ERROR: [batch] ConnectTimeout: HTTPSConnectionPool(host='papago.naver.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000273BFCA4670>, 'Connection to papago.naver.com timed out. (connect timeout=None)'))
Traceback (most recent call last):
  File "F:\1\envs\manga-image-translator\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "F:\1\envs\manga-image-translator\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "F:\1\envs\manga-image-translator\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\1\envs\manga-image-translator\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "F:\1\envs\manga-image-translator\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "F:\1\envs\manga-image-translator\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "F:\1\envs\manga-image-translator\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "F:\1\envs\manga-image-translator\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000273BFCA4670>, 'Connection to papago.naver.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "F:\1\envs\manga-image-translator\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "F:\1\envs\manga-image-translator\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='papago.naver.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000273BFCA4670>, 'Connection to papago.naver.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 66, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 35, in dispatch
    await translator.translate_path(args.input, dest, args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 154, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 173, in _translate_file
    translation_dict = await self.translate(img, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 249, in translate
    return await self._translate(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 338, in _translate
    ctx.text_regions = await self._run_text_translation(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 477, in _run_text_translation
    translated_sentences = await dispatch_translation(ctx.translator, [region.get_text() for region in ctx.text_regions], ctx.use_mtpe,
  File "F:\manga-image-translator\manga_translator\translators\__init__.py", line 106, in dispatch
    queries = await translator.translate('auto', tgt_lang, queries, use_mtpe)
  File "F:\manga-image-translator\manga_translator\translators\common.py", line 167, in translate
    _translations = await self._translate(*self.parse_language_codes(from_lang, to_lang, fatal=True), queries)
  File "F:\manga-image-translator\manga_translator\translators\papago.py", line 36, in _translate
    result = await self._do_request(data, self._version_key)
  File "F:\1\envs\manga-image-translator\lib\functools.py", line 981, in __get__
    val = self.func(instance)
  File "F:\manga-image-translator\manga_translator\translators\papago.py", line 44, in _version_key
    script = requests.get('https://papago.naver.com')
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='papago.naver.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000273BFCA4670>, 'Connection to papago.naver.com timed out. (connect timeout=None)'))
```

**Comment by zyddnys** [comment]
papago timed out is not caused by the project, check your network connection
