### ISSUE TITLE
[Bug]: RuntimeError: Unsupported model revision

### ISSUE THREAD

**Issue by kucingkembar** [zyddnys/manga-image-translator#398]
### Issue

it run without problem at first, 
after some time this problem appear

### Command Line Arguments

```Shell
--mode batch -v --use-cuda-limited --translator=offline -l ENG -i "D:\Users\PCUSER\Documents\Mangas"
```

### Console logs

```Shell
[batch] Running text translation
[SelectiveOfflineTranslator] Selected translator: SugoiTranslator
ERROR: [batch] RuntimeError: Unsupported model revision. This executable supports models with revision v5 or below, but the model has revision v6. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)
Traceback (most recent call last):
  File "E:\manga-image-translator\manga_translator\__main__.py", line 74, in <module>
    loop.run_until_complete(dispatch(args))
  File "C:\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "E:\manga-image-translator\manga_translator\__main__.py", line 43, in dispatch
    await translator.translate_path(path, dest, args_dict)
  File "E:\manga-image-translator\manga_translator\manga_translator.py", line 157, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "E:\manga-image-translator\manga_translator\manga_translator.py", line 177, in _translate_file
    translation_dict = await self.translate(img, params)
  File "E:\manga-image-translator\manga_translator\manga_translator.py", line 253, in translate
    return await self._translate(ctx)
  File "E:\manga-image-translator\manga_translator\manga_translator.py", line 342, in _translate
    ctx.text_regions = await self._run_text_translation(ctx)
  File "E:\manga-image-translator\manga_translator\manga_translator.py", line 481, in _run_text_translation
    translated_sentences = await dispatch_translation(ctx.translator, [region.get_text() for region in ctx.text_regions], ctx.use_mtpe,
  File "E:\manga-image-translator\manga_translator\translators\__init__.py", line 106, in dispatch
    queries = await translator.translate('auto', tgt_lang, queries, use_mtpe)
  File "E:\manga-image-translator\manga_translator\translators\selective.py", line 49, in translate
    await self._real_translator.load(*self._cached_load_params)
  File "E:\manga-image-translator\manga_translator\translators\common.py", line 290, in load
    return await super().load(device, *self.parse_language_codes(from_lang, to_lang))
  File "E:\manga-image-translator\manga_translator\utils\inference.py", line 315, in load
    await self._load(*args, **kwargs, device=device)
  File "E:\manga-image-translator\manga_translator\translators\sugoi.py", line 168, in _load
    await super()._load(from_lang, to_lang, device)
  File "E:\manga-image-translator\manga_translator\translators\sugoi.py", line 71, in _load
    self.model = ctranslate2.Translator(
RuntimeError: Unsupported model revision. This executable supports models with revision v5 or below, but the model has revision v6. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)
```

**Comment by JustFrederik** [comment]
Update your dependencies

**Comment by kucingkembar** [comment]
sorry for the late reply, I have some problem with the Cuda, 

to [JustFrederik](https://github.com/JustFrederik) and [thatDudo](https://github.com/thatDudo)
thank you,
