### ISSUE TITLE
[Bug]: ERROR: [batch] AssertionError:

### ISSUE THREAD

**Issue by kucingkembar** [zyddnys/manga-image-translator#409]
### Issue

can you skip the errored picture process and then start the next file in the batch?

### Command Line Arguments

```Shell
--mode batch -v --use-cuda-limited --translator=offline -l ENG -i "D:\Users\PCUSER\Documents\Mangas"
```

### Console logs

```Shell
ERROR: [batch] AssertionError:
Traceback (most recent call last):
  File "E:\manga-image-translator\manga_translator\__main__.py", line 74, in <module>
    loop.run_until_complete(dispatch(args))
  File "C:\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "E:\manga-image-translator\manga_translator\__main__.py", line 43, in dispatch
    await translator.translate_path(path, dest, args_dict)
  File "E:\manga-image-translator\manga_translator\manga_translator.py", line 159, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "E:\manga-image-translator\manga_translator\manga_translator.py", line 181, in _translate_file
    translation_dict = await self.translate(img, params)
  File "E:\manga-image-translator\manga_translator\manga_translator.py", line 259, in translate
    return await self._translate(ctx)
  File "E:\manga-image-translator\manga_translator\manga_translator.py", line 351, in _translate
    ctx.text_regions = await self._run_textline_merge(ctx)
  File "E:\manga-image-translator\manga_translator\manga_translator.py", line 421, in _run_textline_merge
    text_regions = await dispatch_textline_merge(ctx.textlines, *ctx.img_rgb.shape[:2], verbose=self.verbose)
  File "E:\manga-image-translator\manga_translator\textline_merge\__init__.py", line 169, in dispatch
    for (txtlns, fg_color, bg_color) in merge_bboxes_text_region(textlines, width, height):
  File "E:\manga-image-translator\manga_translator\textline_merge\__init__.py", line 117, in merge_bboxes_text_region
    region_indices.extend(split_text_region(bboxes, node_set, width, height))
  File "E:\manga-image-translator\manga_translator\textline_merge\__init__.py", line 45, in split_text_region
    G.add_edge(u, v, weight=bboxes[u].distance(bboxes[v]))
  File "E:\manga-image-translator\manga_translator\utils\general.py", line 496, in distance
    return self.distance_impl(other, rho)# + 1000 * abs(self.angle - other.angle)
  File "E:\manga-image-translator\manga_translator\utils\general.py", line 499, in distance_impl
    assert self.assigned_direction == other.assigned_direction
AssertionError
```

**Comment by 1439707509** [comment]
这样不好吧，要是有图片没有处理，那我要怎样知道，如果是加个选项，那还行
