### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dolev765** [zyddnys/manga-image-translator#423]
### Issue

I am getting A Issue I dont understand how to fix

### Command Line Arguments

```Shell
python -m manga_translator -v --mode batch --translator=google -l ENG -i C:\Users\dolev\OneDrive\Pictures\2
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "manga_translator\__init__.py", line 1, in <module>
    import colorama
ImportError: No module named colorama
PS C:\baloon translate\BallonsTranslator\manga-image-translator>
```

**Comment by Tianci-King** [comment]
I have already pip install -r requirements.txt  , but I still have same question , My Mac is M1 air
![Uploading iShot_2024-03-29_16.18.05.png…]()
