### ISSUE TITLE
[Bug]: Chinese path can cause FT_Exception

### ISSUE THREAD

**Issue by liyuheng55555** [zyddnys/manga-image-translator#425]
### Issue

This bug was also mentioned in this [issue](https://github.com/zyddnys/manga-image-translator/issues/57) and this [issue](https://github.com/zyddnys/manga-image-translator/issues/375), but seems haven't been solved properly.
I think the actual problem is that **freetype.Face() is not able to handle path including Chinese character**, maybe also cannot handle other non-ascii character.
Exception stack:
```
[demo] Running rendering
E:/重要资料/good/manga-image-translator/fonts/Arial-Unicode-Regular.ttf
ERROR: [demo] FT_Exception: FT_Exception:  (cannot open resource)
Traceback (most recent call last):
  File "E:\重要资料\good\manga-image-translator\manga_translator\__main__.py", line 74, in <module>
    loop.run_until_complete(dispatch(args))
  File "E:\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\重要资料\good\manga-image-translator\manga_translator\__main__.py", line 38, in dispatch
    await translator.translate_path(args.input[0], dest, args_dict)
  File "E:\重要资料\good\manga-image-translator\manga_translator\manga_translator.py", line 133, in translate_path
    await self._translate_file(path, _dest, params)
  File "E:\重要资料\good\manga-image-translator\manga_translator\manga_translator.py", line 179, in _translate_file
    translation_dict = await self.translate(img, params)
  File "E:\重要资料\good\manga-image-translator\manga_translator\manga_translator.py", line 253, in translate
    return await self._translate(ctx)
  File "E:\重要资料\good\manga-image-translator\manga_translator\manga_translator.py", line 375, in _translate
    ctx.img_rendered = await self._run_text_rendering(ctx)
  File "E:\重要资料\good\manga-image-translator\manga_translator\manga_translator.py", line 460, in _run_text_rendering
    output = await dispatch_rendering(ctx.img_inpainted, ctx.text_regions, ctx.font_path, ctx.font_size, ctx.font_size_offset,
  File "E:\重要资料\good\manga-image-translator\manga_translator\rendering\__init__.py", line 101, in dispatch
    text_render.set_font(font_path)
  File "E:\重要资料\good\manga-image-translator\manga_translator\rendering\text_render.py", line 134, in set_font
    FONT_SELECTION = [get_cached_font(p) for p in selection]
  File "E:\重要资料\good\manga-image-translator\manga_translator\rendering\text_render.py", line 134, in <listcomp>
    FONT_SELECTION = [get_cached_font(p) for p in selection]
  File "E:\重要资料\good\manga-image-translator\manga_translator\rendering\text_render.py", line 125, in get_cached_font
    font_cache[path] = freetype.Face(path)
  File "E:\Python\Python310\lib\site-packages\freetype\__init__.py", line 1192, in __init__
    raise FT_Exception(error)
freetype.ft_errors.FT_Exception: FT_Exception:  (cannot open resource)
```

**Comment by zyddnys** [comment]
This is freetype's issue not ours, solution is to not use non-ascii path
