### ISSUE TITLE
Batch Mode Error after latest update

### ISSUE THREAD

**Issue by bregassa** [zyddnys/manga-image-translator#43]
Single Mode work fine, but I get this error with batch mode after the update

```
F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main>python translate_demo.py --mode batch --image F:\lime_message\ --use-inpainting --verbose --translator=google --target-lang=ENG

Namespace(mode='batch', image='F:\\lime_message\\', image_dst='', size=1536, use_inpainting=True, use_cuda=False, force_horizontal=False, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, text_mag_ratio=1, translator='google', target_lang='ENG', use_ctd=False, verbose=True)

 -- Loading models
Processing image in source directory
Processing F:\lime_message\desktop.ini -> F:\lime_message-translated\desktop.ini

Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\im28a.png -> F:\lime_message-translated\im28a.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\im28b.png -> F:\lime_message-translated\im28b.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\im29a.png -> F:\lime_message-translated\im29a.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\im29b.png -> F:\lime_message-translated\im29b.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\im29c.png -> F:\lime_message-translated\im29c.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_2_01.png -> F:\lime_message-translated\lime02_2_01.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_2_02.png -> F:\lime_message-translated\lime02_2_02.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_2_03.png -> F:\lime_message-translated\lime02_2_03.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_01.png -> F:\lime_message-translated\lime02_3_01.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_02.png -> F:\lime_message-translated\lime02_3_02.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_03.png -> F:\lime_message-translated\lime02_3_03.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_04.png -> F:\lime_message-translated\lime02_3_04.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_05.png -> F:\lime_message-translated\lime02_3_05.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_06.png -> F:\lime_message-translated\lime02_3_06.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_07.png -> F:\lime_message-translated\lime02_3_07.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_08.png -> F:\lime_message-translated\lime02_3_08.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_09.png -> F:\lime_message-translated\lime02_3_09.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_10.png -> F:\lime_message-translated\lime02_3_10.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_11.png -> F:\lime_message-translated\lime02_3_11.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_12.png -> F:\lime_message-translated\lime02_3_12.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_13.png -> F:\lime_message-translated\lime02_3_13.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_14.png -> F:\lime_message-translated\lime02_3_14.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_15.png -> F:\lime_message-translated\lime02_3_15.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_16.png -> F:\lime_message-translated\lime02_3_16.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_17.png -> F:\lime_message-translated\lime02_3_17.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_18.png -> F:\lime_message-translated\lime02_3_18.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_19.png -> F:\lime_message-translated\lime02_3_19.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_3_20.png -> F:\lime_message-translated\lime02_3_20.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_5_01.png -> F:\lime_message-translated\lime02_5_01.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_5_02.png -> F:\lime_message-translated\lime02_5_02.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_5_03.png -> F:\lime_message-translated\lime02_5_03.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_5_04.png -> F:\lime_message-translated\lime02_5_04.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_5_05.png -> F:\lime_message-translated\lime02_5_05.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_5_06.png -> F:\lime_message-translated\lime02_5_06.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_5_07.png -> F:\lime_message-translated\lime02_5_07.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_5_08.png -> F:\lime_message-translated\lime02_5_08.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
    await infer(img, 'demo', '', dst_image_name = dst_filename, alpha_ch = alpha_ch)
UnboundLocalError: local variable 'img' referenced before assignment
Processing F:\lime_message\lime02_6_01.png -> F:\lime_message-translated\lime02_6_01.png
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 273, in main
```

**Comment by zyddnys** [comment]
fixed

**Comment by bregassa** [comment]
thanks, it work.
