### ISSUE TITLE
[Bug]: Not able to run it

### ISSUE THREAD

**Issue by iMuhammed1996** [zyddnys/manga-image-translator#434]
### Issue

I'm sure all modules and tools are installed, but still getting the same error mentioned bellow. Tried both windows and mac and no outcome. 
Python version: Python 3.9.1

### Command Line Arguments

```Shell
python manga_translator\manga_translator.py
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\tesla\Documents\manga-image-translator\manga_translator\manga_translator.py", line 21, in <module>
    from manga_translator.utils.threading import Throttler
  File "C:\Users\tesla\Documents\manga-image-translator\manga_translator\manga_translator.py", line 21, in <module>
    from manga_translator.utils.threading import Throttler
ModuleNotFoundError: No module named 'manga_translator.utils'; 'manga_translator' is not a package
```

**Comment by zyddnys** [comment]
Use `python -m manga_translator`, do not directly launch manga_translator.py
