### ISSUE TITLE
[Bug]: 运行报错

### ISSUE THREAD

**Issue by 5536086** [zyddnys/manga-image-translator#435]
### Issue

环境：
debian11+python3.9.9

pydensecrf也已经安装

### Command Line Arguments

```Shell
python3 -m manga_translator --verbose --mode web
```

### Console logs

```Shell
root@vps-c645befc:~/manga-image-translator# python3 -m manga_translator --verbose --mode web
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/manga-image-translator/manga_translator/__init__.py", line 7, in <module>
    from .manga_translator import *
  File "/root/manga-image-translator/manga_translator/manga_translator.py", line 6, in <module>
    import cv2
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by zyddnys** [comment]
安装`pip install opencv-python-headless`
