### ISSUE TITLE
[Bug]: ERROR: [batch] TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#455]
### Issue

ERROR: [batch] TypeError: 'int' object is not subscriptable

### Command Line Arguments

```Shell
python -m manga_translator -v --mode batch --use-cuda --translator=m2m100_big -l RUS --font-path=fonts/anime_ace.ttf -i
```

### Console logs

```Shell
[batch] Loading models
[batch] Running text detection
[DefaultDetector] Detection resolution: 1024x1536
[batch] Running ocr
[Model48pxCTCOCR] prob: 0.9999666000300732 LUKA! fg: (1, 1, 3) bg: (2, 1, 3)
[Model48pxCTCOCR] prob: 0.9999939442211243 LUKA? fg: (1, 1, 2) bg: (1, 1, 4)
[Model48pxCTCOCR] prob: 0.9992131948683326 *** fg: (1, 3, 4) bg: (1, 2, 4)
[Model48pxCTCOCR] prob: 0.9996079638707932 *** fg: (1, 2, 4) bg: (2, 2, 4)
[Model48pxCTCOCR] prob: 0.9995093677256559 *** fg: (0, 2, 2) bg: (0, 3, 2)
[batch] Running text translation
[GoogleTranslator] Translating into Russian
[GoogleTranslator] 0: *****
[GoogleTranslator] 1: *****
[batch] Running mask refinement
[mask]: 100%|██████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 151.51it/s]
[LamaMPEInpainter] Inpainting resolution: 800x1280
[batch] Running rendering
[render] font_size_minimum 14
[render]:   0%|
ERROR: [batch] TypeError: 'int' object is not subscriptable
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 42, in dispatch
    await translator.translate_path(path, dest, args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 160, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 182, in _translate_file
    translation_dict = await self.translate(img, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 248, in translate
    return await self._translate(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 388, in _translate
    ctx.img_rendered = await self._run_text_rendering(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 476, in _run_text_rendering
    output = await dispatch_rendering(ctx.img_inpainted, ctx.text_regions, ctx.font_path, ctx.font_size, ctx.font_size_offset,
  File "F:\manga-image-translator\manga_translator\rendering\__init__.py", line 116, in dispatch
    img = render(img, region, dst_points, hyphenate)
  File "F:\manga-image-translator\manga_translator\rendering\__init__.py", line 134, in render
    temp_box = text_render.put_text_horizontal(
  File "F:\manga-image-translator\manga_translator\rendering\text_render.py", line 657, in put_text_horizontal
    line_text_list, line_width_list = calc_horizontal(font_size, text, width, height, lang, hyphenate)
  File "F:\manga-image-translator\manga_translator\rendering\text_render.py", line 514, in calc_horizontal
    if line_idx < len(line_width_list) - 2 and word_idx == line_width_list[line_idx + 2][0]:
TypeError: 'int' object is not subscriptable
```
Entrance photo
![input](https://github.com/zyddnys/manga-image-translator/assets/49092250/92ad118e-d612-4237-a679-084703dcce81)
[log.txt](https://github.com/zyddnys/manga-image-translator/files/12565493/log.txt)

**Comment by My12123** [comment]
@zyddnys @thatDudo 
How to fix?

**Comment by thatDudo** [comment]
I have switched up a variable name there. Thanks.
