### ISSUE TITLE
[Bug]: ERROR: [batch] TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#458]
### Issue

ERROR: [batch] TypeError: slice indices must be integers or None or have an __index__ method

### Command Line Arguments

```Shell
python -m manga_translator -v --mode batch --use-cuda --translator=m2m100_big -l RUS --font-path=fonts/anime_ace.ttf -i
```

### Console logs

```Shell
ERROR: [batch] TypeError: slice indices must be integers or None or have an __index__ method
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 42, in dispatch
    await translator.translate_path(path, dest, args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 160, in translate_path
    if await self._translate_file(file_path, output_dest, params):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 182, in _translate_file
    translation_dict = await self.translate(img, params)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 248, in translate
    return await self._translate(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 388, in _translate
    ctx.img_rendered = await self._run_text_rendering(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 476, in _run_text_rendering
    output = await dispatch_rendering(ctx.img_inpainted, ctx.text_regions, ctx.font_path, ctx.font_size, ctx.font_size_offset,
  File "F:\manga-image-translator\manga_translator\rendering\__init__.py", line 116, in dispatch
    img = render(img, region, dst_points, hyphenate)
  File "F:\manga-image-translator\manga_translator\rendering\__init__.py", line 134, in render
    temp_box = text_render.put_text_horizontal(
  File "F:\manga-image-translator\manga_translator\rendering\text_render.py", line 693, in put_text_horizontal
    offset_x = put_char_horizontal(font_size, c, pen_line, canvas_text, canvas_border, border_size=bg_size)
  File "F:\manga-image-translator\manga_translator\rendering\text_render.py", line 631, in put_char_horizontal
    canvas_text[pen[1]:pen[1]+bitmap.rows, pen[0]:pen[0]+bitmap.width] = bitmap_char
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by My12123** [comment]
@zyddnys @thatDudo
Please check for the ability to work on different operating systems and execution tools before publishing any changes.

**Comment by thatDudo** [comment]
This is because of the rendering update I made, it is still a little bit buggy but it worked on the images I tested. It is not because of the os but because of the image you supplied.
But youre right I shouldve tested it out more.

**Comment by thatDudo** [comment]
Can you test if it works now or send the image?

**Comment by My12123** [comment]
@thatDudo 
It works, but it takes up more memory.
![2023-09-11_16-09-17](https://github.com/zyddnys/manga-image-translator/assets/49092250/1178419a-4510-4814-8246-be58d6805372)

**Comment by thatDudo** [comment]
Are you sure because I dont think I have made any changes that could cause that...

**Comment by My12123** [comment]
Yes, I'm sure, it usually deals with 7.6 GB. Can you check?
