### ISSUE TITLE
[Bug]: ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by SchizoidLifter** [zyddnys/manga-image-translator#473]
### Issue

This error occurs randomly and I don't have any exact steps to reproduce it.
Usually it'll translate a few pages properly before running into the error. Then I have to reuse the command to get it to translate a few more pages before it runs into that same error. After a few cycles the error stops occurring.

I did a small bit of testing and found it's not related to the -f format 

### Command Line Arguments

```Shell
python -m manga_translator -v --mode batch --translator=gpt3.5 -l ENG "path/to/images" -f xcf --mangatoeng
```

### Console logs

```Shell
User:
<|1|>血風霧戦を
<|2|>止めた⁉
[GPT35TurboTranslator] -- GPT Response --
<|1|>Put an end to the fierce battle!?
[GPT35TurboTranslator] ['Put an end to the fierce battle!?']
[GPT35TurboTranslator] Used 105 tokens (Total: 326)
[GPT35TurboTranslator] 0: 血風霧戦を => Putting an end to the Battle of Blood, Wind, and Mist⁉
[GPT35TurboTranslator] 1: 止めた⁉ =>
[batch] Running mask refinement
[mask]: 100%|███████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 208.39it/s]
[LamaMPEInpainter] Inpainting resolution: 1072x1600
[batch] Running rendering
ERROR: [batch] ZeroDivisionError: division by zero
Traceback (most recent call last):
File "C:\Users\Catsb\manga-image-translator\manga_translator\__main__.py", line 73, in <module>
loop.run_until_complete(dispatch(args))
File "C:\Users\Catsb\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
return future.result()
File "C:\Users\Catsb\manga-image-translator\manga_translator\__main__.py", line 42, in dispatch
await translator.translate_path(path, dest, args_dict)
File "C:\Users\Catsb\manga-image-translator\manga_translator\manga_translator.py", line 161, in translate_path
if await self._translate_file(file_path, output_dest, params):
File "C:\Users\Catsb\manga-image-translator\manga_translator\manga_translator.py", line 183, in _translate_file
translation_dict = await self.translate(img, params)
File "C:\Users\Catsb\manga-image-translator\manga_translator\manga_translator.py", line 249, in translate
return await self._translate(ctx)
File "C:\Users\Catsb\manga-image-translator\manga_translator\manga_translator.py", line 399, in _translate
ctx.img_rendered = await self._run_text_rendering(ctx)
File "C:\Users\Catsb\manga-image-translator\manga_translator\manga_translator.py", line 495, in _run_text_rendering
output = await dispatch_eng_render(ctx.img_inpainted, ctx.img_rgb, ctx.text_regions, ctx.font_path)
File "C:\Users\Catsb\manga-image-translator\manga_translator\rendering\__init__.py", line 188, in dispatch_eng_render
return render_textblock_list_eng(img_canvas, text_regions, size_tol=1.2, original_img=original_img, downscale_constraint=0.8)
File "C:\Users\Catsb\manga-image-translator\manga_translator\rendering\text_render_eng.py", line 469, in render_textblock_list_eng
lines_needed = len(region.translation) / len(base_length_word)
ZeroDivisionError: division by zero
```

**Comment by zyddnys** [comment]
for some reason gpt3.5 translate "止めた⁉" into nothing, that's causing the division by zero, i will skip empty translation now

**Comment by ColdTearsYY** [comment]
又出现了
