### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by sangrime** [zyddnys/manga-image-translator#5]
Thanks for your great support.

Traceback (most recent call last):
  File "/Users/tony/IPANDALAB Dropbox/Oh Tony/project/Python/manga-image-translator/translate_demo.py", line 647, in <module>
    main()
  File "/Users/tony/IPANDALAB Dropbox/Oh Tony/project/Python/manga-image-translator/translate_demo.py", line 525, in main
    boxes, scores = det({'shape':[(img_resized.shape[0], img_resized.shape[1])]}, db)
  File "/Users/tony/IPANDALAB Dropbox/Oh Tony/project/Python/manga-image-translator/dbnet_utils.py", line 38, in __call__
    boxes, scores = self.boxes_from_bitmap(pred[batch_index], segmentation[batch_index], width, height)
  File "/Users/tony/IPANDALAB Dropbox/Oh Tony/project/Python/manga-image-translator/dbnet_utils.py", line 105, in boxes_from_bitmap
    contours, _ = cv2.findContours((bitmap * 255).astype(np.uint8), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)

I've meet the error.

Can you explain what i can do?

Thanks

**Comment by zyddnys** [comment]
I don't know what could have caused such error, but I can make the error disappear so not to crash the program. (https://github.com/zyddnys/manga-image-translator/commit/b169b28a30c75c1391ef2e3890665eac11a432c4)
If you find any more errors you can send me your input image and parameters so I can reproduce them.

**Comment by sangrime** [comment]
Thank for your great support!
