### ISSUE TITLE
[Bug]: ValueError: Word to be hyphenated may have at most 100 characters.

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#500]
### Issue

ValueError: Word to be hyphenated may have at most 100 characters.

### Command Line Arguments

```Shell
python -m manga_translator -v --mode batch --use-cuda --translator=m2m100_big -l RUS --font-path=fonts/anime_ace.ttf -i
```

### Console logs

```Shell
ERROR: [batch] ValueError: Word to be hyphenated may have at most 100 characters.
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 42, in dispatch
    await translator.translate_path(path, dest, args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 175, in translate_path
    if await self.translate_file(file_path, output_dest, params):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 202, in translate_file
    return await self._translate_file(path, dest, ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 245, in _translate_file
    ctx = await self.translate(img, ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 303, in translate
    return await self._translate(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 445, in _translate
    ctx.img_rendered = await self._run_text_rendering(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 549, in _run_text_rendering
    output = await dispatch_rendering(ctx.img_inpainted, ctx.text_regions, ctx.font_path, ctx.font_size,
  File "F:\manga-image-translator\manga_translator\rendering\__init__.py", line 117, in dispatch
    img = render(img, region, dst_points, hyphenate, line_spacing)
  File "F:\manga-image-translator\manga_translator\rendering\__init__.py", line 136, in render
    temp_box = text_render.put_text_horizontal(
  File "F:\manga-image-translator\manga_translator\rendering\text_render.py", line 675, in put_text_horizontal
    line_text_list, line_width_list = calc_horizontal(font_size, text, width, height, lang, hyphenate)
  File "F:\manga-image-translator\manga_translator\rendering\text_render.py", line 407, in calc_horizontal
    new_syls = hyphenator.syllables(word)
  File "F:\1\envs\manga-image-translator\lib\site-packages\hyphen\hyphenator.py", line 132, in syllables
    return self.apply(word, mode).split('=')
ValueError: Word to be hyphenated may have at most 100 characters.
```
![027 (convert io)](https://github.com/zyddnys/manga-image-translator/assets/49092250/4e7fdcad-961b-4dcc-a27e-0c7ee6835c01)

![023 (convert io)](https://github.com/zyddnys/manga-image-translator/assets/49092250/b2dc9298-ef4a-414d-8623-74ef5ac1ffd2)
```
[batch] Translating: "G:\XXX Class_ Adult Lecture\Новая папка\Part 2 [END]\023.webp"
[batch] Loading models
[batch] Running text detection
[DefaultDetector] Detection resolution: 1280x1536
[batch] Running ocr
[Model48pxCTCOCR] prob: 0.9990088253436769 MY fg: (2, 2, 4) bg: (3, 4, 4)
[Model48pxCTCOCR] prob: 0.9983511095745838 AAA fg: (7, 7, 8) bg: (9, 7, 10)
[Model48pxCTCOCR] prob: 0.9978561566332994 AAA fg: (5, 5, 8) bg: (9, 5, 12)
[Model48pxCTCOCR] prob: 0.9996961287459528 AAA fg: (6, 4, 5) bg: (7, 4, 7)
[Model48pxCTCOCR] prob: 0.9994530980301635 AAA fg: (4, 4, 6) bg: (7, 5, 8)
[Model48pxCTCOCR] prob: 0.9987778857509224 AAA fg: (5, 5, 8) bg: (7, 5, 11)
[Model48pxCTCOCR] prob: 0.9651663297340259 AAA fg: (7, 6, 6) bg: (7, 8, 8)
[Model48pxCTCOCR] prob: 0.9998744504322149 AAH fg: (2, 2, 7) bg: (4, 3, 9)
[Model48pxCTCOCR] prob: 0.9859269982145681 Seo. fg: (11, 14, 15) bg: (10, 12, 13)
[Model48pxCTCOCR] prob: 0.9997037339461705 HHH fg: (5, 2, 7) bg: (6, 3, 8)
[Model48pxCTCOCR] prob: 0.822517693019613 Haa.. fg: (9, 13, 12) bg: (7, 12, 10)
[Model48pxCTCOCR] prob: 0.8734165502154293 haa.. fg: (10, 14, 17) bg: (10, 13, 15)
[Model48pxCTCOCR] prob: 0.894560922716795 ...UGH. fg: (12, 15, 12) bg: (11, 15, 10)
[Model48pxCTCOCR] prob: 0.9996520693138791 WELL, fg: (4, 6, 7) bg: (5, 7, 7)
[Model48pxCTCOCR] prob: 0.8406752375583498 ...IS IT fg: (3, 5, 8) bg: (5, 6, 7)
[Model48pxCTCOCR] prob: 0.9606922281225224 I HEARD fg: (3, 4, 5) bg: (2, 4, 5)
[Model48pxCTCOCR] prob: 0.9993553449136832 FAULT? fg: (1, 1, 4) bg: (1, 1, 5)
[Model48pxCTCOCR] prob: 0.9917217555459392 GOOD AT fg: (4, 5, 6) bg: (4, 5, 7)
[Model48pxCTCOCR] prob: 0.9988380469313317 YOU CAN'T fg: (3, 3, 7) bg: (4, 2, 8)
[Model48pxCTCOCR] prob: 0.9884197399382361 YOU WERE fg: (3, 6, 6) bg: (2, 6, 5)
[Model48pxCTCOCR] prob: 0.998704641642827 GET HARD! fg: (3, 4, 6) bg: (3, 3, 6)
[Model48pxCTCOCR] prob: 0.9884685542932543 I MEAN... fg: (4, 4, 5) bg: (4, 3, 5)
[Model48pxCTCOCR] prob: 0.9778862271019453 RUNNING... fg: (12, 11, 12) bg: (13, 11, 11)
[Model48pxCTCOCR] prob: 0.9999116485297841 RETIRING? fg: (2, 3, 1) bg: (3, 4, 2)
[Model48pxCTCOCR] prob: 0.9999524406921072 TRUE YOU'RE fg: (3, 4, 8) bg: (3, 5, 7)
[Model48pxCTCOCR] prob: 0.9533273864810936 ALWAYS REALLY fg: (8, 8, 9) bg: (10, 9, 9)
[batch] Running text translation
[GoogleTranslator] Translating into Russian
[GoogleTranslator] 0: ...UGH. YOU WERE ALWAYS REALLY GOOD AT RUNNING... => ...тьфу. Ты всегда был очень хорош в беге...
[GoogleTranslator] 1: Haa.. => Хаа..
[GoogleTranslator] 2: haa.. => хаа..
[GoogleTranslator] 3: Seo. => Сео
[GoogleTranslator] 4: ...IS IT TRUE YOU'RE RETIRING? => ...это правда, что ты уходишь на пенсию?
[GoogleTranslator] 5: WELL, I MEAN... => Ну, я имею в виду...
[GoogleTranslator] 6: I HEARD YOU CAN'T GET HARD! => Я слышал, что ты не можешь стать тяжелым!
[GoogleTranslator] 7: AAA AAA AAA AAA AAA AAA => Ааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааа
[GoogleTranslator] 8: AAH => Ааааааааааааааааааааа
[GoogleTranslator] 9: HHH => ХХХ
[GoogleTranslator] 10: MY FAULT? => МОЯ ВИНА?
[batch] Running mask refinement
[mask]: 100%|██████████████████████████████████████████████████████████████████████████| 26/26 [00:00<00:00, 86.38it/s]
[LamaLargeInpainter] Inpainting resolution: 1176x1696
[batch] Running rendering
[render] font_size_minimum 14
[render]:  64%|██████████████████████████████████████████████▍                          | 7/11 [00:00<00:00, 35.90it/s]
ERROR: [batch] ValueError: Word to be hyphenated may have at most 100 characters.
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 42, in dispatch
    await translator.translate_path(path, dest, args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 175, in translate_path
    if await self.translate_file(file_path, output_dest, params):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 202, in translate_file
    return await self._translate_file(path, dest, ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 245, in _translate_file
    ctx = await self.translate(img, ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 303, in translate
    return await self._translate(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 445, in _translate
    ctx.img_rendered = await self._run_text_rendering(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 549, in _run_text_rendering
    output = await dispatch_rendering(ctx.img_inpainted, ctx.text_regions, ctx.font_path, ctx.font_size,
  File "F:\manga-image-translator\manga_translator\rendering\__init__.py", line 117, in dispatch
    img = render(img, region, dst_points, hyphenate, line_spacing)
  File "F:\manga-image-translator\manga_translator\rendering\__init__.py", line 136, in render
    temp_box = text_render.put_text_horizontal(
  File "F:\manga-image-translator\manga_translator\rendering\text_render.py", line 675, in put_text_horizontal
    line_text_list, line_width_list = calc_horizontal(font_size, text, width, height, lang, hyphenate)
  File "F:\manga-image-translator\manga_translator\rendering\text_render.py", line 407, in calc_horizontal
    new_syls = hyphenator.syllables(word)
  File "F:\1\envs\manga-image-translator\lib\site-packages\hyphen\hyphenator.py", line 132, in syllables
    return self.apply(word, mode).split('=')
ValueError: Word to be hyphenated may have at most 100 characters.
```

**Comment by My12123** [comment]
```
[batch] Translating: "G:\Going To Bed With My Hater\Chapter 11\068.webp"
[batch] Loading models
[batch] Running text detection
[DefaultDetector] Detection resolution: 1536x1024
[batch] Running ocr
[Model48pxCTCOCR] prob: 0.987088013092044 Story by: Gadein fg: (47, 58, 101) bg: (47, 59, 102)
[Model48pxCTCOCR] prob: 0.983628586970345 Art by: Eunlang fg: (31, 43, 77) bg: (32, 44, 78)
[Model48pxCTCOCR] prob: 0.9750144226425291 Produced by: NHN fg: (59, 73, 137) bg: (60, 73, 138)
[Model48pxCTCOCR] prob: 0.9821776444665352 Background art by: paran fg: (60, 81, 139) bg: (63, 84, 141)
[Model48pxCTCOCR] prob: 0.9681196247520351 Original by: Lee Da-woni fg: (37, 48, 82) bg: (42, 52, 85)
[Model48pxCTCOCR] prob: 0.9950371817854697 TO BE CONTINUED... fg: (4, 6, 4) bg: (5, 7, 3)
[Model48pxCTCOCR] prob: 0.9634114300184975 Translation by: So Young Kwon fg: (51, 60, 99) bg: (54, 62, 101)
[Model48pxCTCOCR] prob: 0.6578076239453273 THISWORHIETHEFROFERTYOFNHNHNDISPRLTECTEOHTHENTERHATILFHTLI fg: (12, 10, 10) bg: (16, 10, 16)
[Model48pxCTCOCR] prob: 0.5672896272531955 NUHHRTUFTHISWERHMHEEREPREDUCEODISTREUTEOETBHMITTEDINHFENHHIEHNS fg: (11, 12, 8) bg: (14, 11, 10)
[batch] Running text translation
[M2M100BigTranslator] Translating into Russian
[M2M100BigTranslator] 0: TO BE CONTINUED... => Чтобы быть продолженным...
[M2M100BigTranslator] 1: Original by: Lee Da-woni Story by: Gadein Art by: Eunlang Background art by: paran Produced by: NHN Translation by: So Young Kwon => Оригинальное произведение: Ли Да-Вони История по : Гадейн Художественное изобретение Поверхностное искусство, созданные им. Параном Произведено компанией НХН Перевод на английском языке со словами So Young Kwon
[M2M100BigTranslator] 2: THISWORHIETHEFROFERTYOFNHNHNDISPRLTECTEOHTHENTERHATILFHTLI => THISWORHIETHEFROFERTYOFNHNDIESPRLTECTEOHT HENTERHAATILFTLI
[M2M100BigTranslator] 3: NUHHRTUFTHISWERHMHEEREPREDUCEODISTREUTEOETBHMITTEDINHFENHHIEHNS => NUHHRTUFTHISWERHRMHEEREПредшествующееРазвитиеДистрибьютеОЭТБМиттДинхфенхайнс
[batch] Running mask refinement
[mask]: 100%|████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 83.33it/s]
[LamaLargeInpainter] Inpainting resolution: 800x432
[batch] Running rendering
[render] font_size_minimum 6
[render]:  75%|███████████████████████████████████████████████████████▌                  | 3/4 [00:00<00:00, 32.26it/s]
ERROR: [batch] ValueError: Word to be hyphenated may have at most 100 characters.
Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 42, in dispatch
    await translator.translate_path(path, dest, args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 175, in translate_path
    if await self.translate_file(file_path, output_dest, params):
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 202, in translate_file
    return await self._translate_file(path, dest, ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 245, in _translate_file
    ctx = await self.translate(img, ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 303, in translate
    return await self._translate(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 445, in _translate
    ctx.img_rendered = await self._run_text_rendering(ctx)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 549, in _run_text_rendering
    output = await dispatch_rendering(ctx.img_inpainted, ctx.text_regions, ctx.font_path, ctx.font_size,
  File "F:\manga-image-translator\manga_translator\rendering\__init__.py", line 117, in dispatch
    img = render(img, region, dst_points, hyphenate, line_spacing)
  File "F:\manga-image-translator\manga_translator\rendering\__init__.py", line 136, in render
    temp_box = text_render.put_text_horizontal(
  File "F:\manga-image-translator\manga_translator\rendering\text_render.py", line 675, in put_text_horizontal
    line_text_list, line_width_list = calc_horizontal(font_size, text, width, height, lang, hyphenate)
  File "F:\manga-image-translator\manga_translator\rendering\text_render.py", line 407, in calc_horizontal
    new_syls = hyphenator.syllables(word)
  File "F:\1\envs\manga-image-translator\lib\site-packages\hyphen\hyphenator.py", line 132, in syllables
    return self.apply(word, mode).split('=')
ValueError: Word to be hyphenated may have at most 100 characters.
```
