### ISSUE TITLE
[Bug]: ERROR: [web_client] ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5003): Max retries exceeded with url: /connect-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#508]
### Issue

ERROR: [web_client] ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5003): Max retries exceeded with url: /connect-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0

### Command Line Arguments

```Shell
python -m manga_translator -v --mode web_client --use-cuda --translator=m2m100_big -l RUS --font-path=fonts/anime_ace.ttf
```

### Console logs

```Shell
(manga-image-translator) F:\manga-image-translator>python -m manga_translator -v --mode web_client --use-cuda --translator=m2m100_big -l RUS --font-path=fonts/anime_ace.ttf
[web_client] Namespace(mode='web_client', input=None, dest='', target_lang='RUS', verbose=True, format=None, attempts=0, ignore_errors=False, overwrite=False, skip_no_text=False, model_dir=None, use_cuda=True, use_cuda_limited=False, detector='default', ocr='48px', inpainter='lama_large', upscaler='esrgan', upscale_ratio=None, colorizer=None, translator='m2m100_big', translator_chain=None, selective_translation=None, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, min_text_length=0, inpainting_size=2048, inpainting_precision='fp32', colorization_size=576, denoise_sigma=30, mask_dilation_offset=0, font_size=None, font_size_offset=0, font_size_minimum=-1, font_color=None, line_spacing=None, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, no_hyphenation=False, manga2eng=False, gpt_config=None, use_mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='fonts/anime_ace.ttf', gimp_font='Sans-serif', host='127.0.0.1', port=5003, nonce='', ws_url='ws://localhost:5000', save_quality=100, ignore_bubble=0)
[web_client] Running in web_client mode
[web_client] Waiting for translation tasks
ERROR: [web_client] ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5003): Max retries exceeded with url: /connect-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020C9A0AB9D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
Traceback (most recent call last):
  File "C:\Users\tchot\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\tchot\AppData\Roaming\Python\Python310\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\tchot\AppData\Roaming\Python\Python310\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tchot\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\tchot\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\tchot\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "F:\1\envs\manga-image-translator\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "F:\1\envs\manga-image-translator\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "F:\1\envs\manga-image-translator\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "F:\1\envs\manga-image-translator\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "F:\1\envs\manga-image-translator\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\tchot\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\tchot\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020C9A0AB9D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\tchot\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "C:\Users\tchot\AppData\Roaming\Python\Python310\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5003): Max retries exceeded with url: /connect-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020C9A0AB9D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\manga-image-translator\manga_translator\__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "F:\1\envs\manga-image-translator\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\manga-image-translator\manga_translator\__main__.py", line 50, in dispatch
    await translator.listen(args_dict)
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 703, in listen
    await self._init_connection()
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 667, in _init_connection
    requests.post(f'http://{self.host}:{self.port}/connect-internal', json=data)
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "F:\1\envs\manga-image-translator\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5003): Max retries exceeded with url: /connect-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020C9A0AB9D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
```

**Comment by thatDudo** [comment]
Use mode web
