### ISSUE TITLE
自动切换翻译器问题

### ISSUE THREAD

**Issue by biandefeng0315** [zyddnys/manga-image-translator#52]
大佬好，我在Windows段执行命令行翻译整个文件夹，发现其中有段问题：
Inpainting resolution: 1360x1920
 -- Translating
oh no.
fail to initialize deepl :
auth_key must not be empty
switch to google translator
 -- Rendering translated text
似乎识别我所选择的翻译器为deepl了，实际上我所执行的为
python translate_demo.py --verbose --mode batch --use-inpainting --use-cuda --translator=baidu --target-lang=CHS --image D:/translate/1234
很显然，我所选择的是百度翻译，但是却切换为了谷歌翻译器了，该如何解决这个问题呢，谢谢！

**Comment by biandefeng0315** [comment]
在这次执行之前，百度api页面上所显示的是正常翻译，代表其实上次翻译是正常使用百度翻译的，但是这次却切换为谷歌了

**Comment by biandefeng0315** [comment]
用有道翻译器也是存在这个问题

**Comment by biandefeng0315** [comment]
问题似乎被解决了,因为用量确实的被记录在平台上，但是现在出现了新的问题，百度翻译器完全无法使用，显示
 -- Translating
oh no.
fail to initialize deepl :
auth_key must not be empty
switch to google translator
Traceback (most recent call last):
  File "D:\translate\manga-image-translator\translate_demo.py", line 326, in <module>
    loop.run_until_complete(main(args.mode))
  File "C:\Users\sola\miniconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\translate\manga-image-translator\translate_demo.py", line 246, in main
    await infer(img, mode, '', alpha_ch = alpha_ch)
  File "D:\translate\manga-image-translator\translate_demo.py", line 160, in infer
    translated_sentences = await run_translation(args.translator, 'auto', args.target_lang, [r.text for r in text_regions])
  File "D:\translate\manga-image-translator\translators\__init__.py", line 186, in dispatch
    result = await BAIDU_CLIENT.translate(src_lang, tgt_lang, concat_texts)
  File "D:\translate\manga-image-translator\translators\baidu.py", line 30, in translate
    for ret in result["trans_result"]:
KeyError: 'trans_result'
我在本地机与另外的远程机器上尝试了，都出现了如示的报错

**Comment by zyddnys** [comment]
translator/keys.py里的百度的key填了吗

**Comment by biandefeng0315** [comment]
> translators/keys.py里的百度的key填了吗

填了

**Comment by biandefeng0315** [comment]
> > translators/keys.py里的百度的key填了吗
> 
> 填了

选的百度，不行，有道就能正常进行

**Comment by zyddnys** [comment]
key可能不对，我这里测的百度没有问题
