### ISSUE TITLE
[Bug]: Output format PSD Error

### ISSUE THREAD

**Issue by Mlegbder** [zyddnys/manga-image-translator#561]
### Issue

Output PSD Error

### Command Line Arguments

```Shell
python -m manga_translator --verbose --mode web --use-gpu -f psd
```

### Console logs

```Shell
[web_client] Saving "D:\manga-image-translator\result\b9c3ee376f9bf98866273bda9cc0c6b111cc932cc6b490c4d8bccc64122ec7a5-1536-google-ENG-default-auto\final.psd"
error: gimp not found in directory: C:\Program Files\GIMP 2\bin\
Task state b9c3ee376f9bf98866273bda9cc0c6b111cc932cc6b490c4d8bccc64122ec7a5-1536-google-ENG-default-auto to {'info': 'error', 'finished': True}
ERROR: [web_client] TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
```

**Comment by Mlegbder** [comment]
After installing GIMP, if you call it again, you will get the following error. :  'gbk' codec can't decode byte 0x82 in position 520: illegal multibyte sequence

**Comment by Mlegbder** [comment]
UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 520: illegal multibyte sequence
=== Output
EEEEeEeek! 2 GeglBuffers leaked

=== Error
None
Task state e9b425a664ad65ac6bbc6934c485e4b079493496c66bc07c4b799e933c4bcb56-1536-google-ENG-default-auto to {'info': 'error', 'finished': True}
ERROR: [web_client] TypeError: argument of type 'NoneType' is not iterable

**Comment by Mlegbder** [comment]
None
Task state e9b425a664ad65ac6bbc6934c485e4b079493496c66bc07c4b799e933c4bcb56-1536-google-ENG-default-auto to {'info': 'error', 'finished': True}
ERROR: [web_client] TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "D:\manga-image-translator\manga_translator\__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\manga-image-translator\manga_translator\__main__.py", line 50, in dispatch
    await translator.listen(args_dict)
  File "D:\manga-image-translator\manga_translator\manga_translator.py", line 729, in listen
    await self.translate_path(self._result_path('input.jpg'), self._result_path('final.jpg'),
  File "D:\manga-image-translator\manga_translator\manga_translator.py", line 152, in translate_path
    await self.translate_file(path, _dest, params)
  File "D:\manga-image-translator\manga_translator\manga_translator.py", line 203, in translate_file
    return await self._translate_file(path, dest, ctx)
  File "D:\manga-image-translator\manga_translator\manga_translator.py", line 255, in _translate_file
    save_result(result, dest, ctx)
  File "D:\manga-image-translator\manga_translator\save.py", line 43, in save_result
    format_handler.save(result, dest, ctx)
  File "D:\manga-image-translator\manga_translator\save.py", line 30, in save
    self._save(result, dest, ctx)
  File "D:\manga-image-translator\manga_translator\save.py", line 66, in _save
    gimp_render(dest, ctx)
  File "D:\manga-image-translator\manga_translator\rendering\gimp_render.py", line 143, in gimp_render
    gimp_batch(full_script)
  File "D:\manga-image-translator\manga_translator\rendering\gimp_render.py", line 190, in gimp_batch
    if "Error:" in result.stderr:
TypeError: argument of type 'NoneType' is not iterable
Restarting translator process
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
