### ISSUE TITLE
[Bug]: ERROR: [web_client] ConnectTimeout

### ISSUE THREAD

**Issue by starise-wg** [zyddnys/manga-image-translator#643]
### Issue

使用http://127.0.0.1:5003/manual-translate接口报错ERROR: [web_client] ConnectTimeout

### Console logs

```Shell
New `manual-translate` task 52baefa10be4840d8d1a911a8ac436c7
{'manual': True, 'created_at': 1718350230.1386235, 'requested_at': 1718350230.1386235}
[web_client] Processing task 52baefa10be4840d8d1a911a8ac436c7
[web_client] Translating: "/root/manga-image-translator/result/52baefa10be4840d8d1a911a8ac436c7/input.jpg"
[web_client] Loading models
[web_client] Running text detection
Task state 52baefa10be4840d8d1a911a8ac436c7 to {'info': 'detection', 'finished': False}
[DefaultDetector] Detection resolution: 1280x1536
[web_client] Running ocr
Task state 52baefa10be4840d8d1a911a8ac436c7 to {'info': 'ocr', 'finished': False}
[Model48pxOCR] prob: 0.4896813631057739 ハ fg: (29, 15, 3) bg: (225, 216, 210)
[Model48pxOCR] prob: 0.999983012676239 とか fg: (6, 5, 2) bg: (6, 5, 2)
[Model48pxOCR] prob: 0.9999671578407288 坂本 fg: (5, 6, 3) bg: (5, 6, 3)
[Model48pxOCR] prob: 0.9996289610862732 くん？ fg: (5, 3, 1) bg: (5, 3, 1)
[Model48pxOCR] prob: 0.9997701644897461 うーん fg: (2, 2, 0) bg: (2, 2, 0)
[Model48pxOCR] prob: 0.9849154949188232 えー、 fg: (3, 5, 3) bg: (3, 5, 3)
[Model48pxOCR] prob: 0.9998421669006348 じゃあ fg: (4, 4, 0) bg: (4, 4, 0)
[Model48pxOCR] prob: 0.9996737837791443 他には？ fg: (4, 3, 2) bg: (4, 3, 2)
[Model48pxOCR] prob: 0.999823808670044 メシアは fg: (4, 3, 2) bg: (4, 3, 2)
[Model48pxOCR] prob: 0.880385160446167 くれてっ： fg: (5, 4, 2) bg: (5, 4, 2)
[Model48pxOCR] prob: 0.9998525381088257 ふふっ、 fg: (4, 3, 1) bg: (4, 3, 1)
[Model48pxOCR] prob: 0.9989321827888489 どうなの？ fg: (4, 5, 5) bg: (4, 5, 5)
[Model48pxOCR] prob: 0.9995644092559814 どう思う？ fg: (5, 4, 1) bg: (5, 4, 1)
[Model48pxOCR] prob: 0.9992502927780151 あっ、あと fg: (2, 3, 1) bg: (2, 3, 1)
[Model48pxOCR] prob: 0.9995983839035034 ねえねえ、 fg: (3, 6, 4) bg: (3, 6, 4)
[Model48pxOCR] prob: 0.9999935030937195 優しいよね fg: (3, 5, 0) bg: (3, 5, 0)
[Model48pxOCR] prob: 0.999058187007904 それだけー？ fg: (9, 8, 7) bg: (9, 8, 7)
[Model48pxOCR] prob: 0.9338704943656921 そうだなあ… fg: (4, 3, 1) bg: (4, 3, 1)
[Model48pxOCR] prob: 0.9999926090240479 髪型変えたら fg: (8, 7, 5) bg: (8, 7, 5)
[Model48pxOCR] prob: 0.9597305059432983 わあ、いいね」 fg: (3, 4, 1) bg: (3, 4, 1)
[Model48pxOCR] prob: 0.9547002911567688 わ、私はー： fg: (3, 2, 1) bg: (3, 2, 1)
[Model48pxOCR] prob: 0.9999563097953796 こないだね、 fg: (3, 3, 0) bg: (3, 3, 0)
[Model48pxOCR] prob: 0.9999973773956299 すぐに気付いて fg: (3, 3, 1) bg: (3, 3, 1)
[Model48pxOCR] prob: 0.9365109205245972 別にそんな‥ fg: (1, 1, 0) bg: (1, 1, 0)
[Model48pxOCR] prob: 0.9997179508209229 面白いなーとか fg: (3, 3, 0) bg: (3, 3, 0)
[Model48pxOCR] prob: 0.999984085559845 反応がいちいち fg: (3, 3, 0) bg: (3, 3, 0)
[Model48pxOCR] prob: 0.999990701675415 めいは坂本のこと fg: (1, 1, 0) bg: (1, 1, 0)
[Model48pxOCR] prob: 0.9984833002090454 敬語使ってて偉いなー fg: (3, 3, 0) bg: (3, 3, 0)
[Model48pxOCR] prob: 0.9999900460243225 店の店員さんとかにも fg: (1, 2, 0) bg: (1, 2, 0)
Task state 52baefa10be4840d8d1a911a8ac436c7 to {'info': 'textline_merge', 'finished': False}
[web_client] Running text translation
Task state 52baefa10be4840d8d1a911a8ac436c7 to {'info': 'translating', 'finished': False}
[GoogleTranslator] Translating into Chinese (Simplified)
Task state 52baefa10be4840d8d1a911a8ac436c7 to {'info': 'error', 'finished': True}
ERROR: [web_client] ConnectTimeout: 
Traceback (most recent call last):
  File "/root/manga-image-translator/manga_translator/__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "/root/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/manga-image-translator/manga_translator/__main__.py", line 50, in dispatch
    await translator.listen(args_dict)
  File "/root/manga-image-translator/manga_translator/manga_translator.py", line 750, in listen
    await self.translate_path(self._result_path('input.jpg'), self._result_path('final.jpg'),
  File "/root/manga-image-translator/manga_translator/manga_translator.py", line 154, in translate_path
    await self.translate_file(path, _dest, params)
  File "/root/manga-image-translator/manga_translator/manga_translator.py", line 205, in translate_file
    return await self._translate_file(path, dest, ctx)
  File "/root/manga-image-translator/manga_translator/manga_translator.py", line 248, in _translate_file
    ctx = await self.translate(img, ctx)
  File "/root/manga-image-translator/manga_translator/manga_translator.py", line 305, in translate
    return await self._translate(ctx)
  File "/root/manga-image-translator/manga_translator/manga_translator.py", line 425, in _translate
    ctx.text_regions = await self._run_text_translation(ctx)
  File "/root/manga-image-translator/manga_translator/manga_translator.py", line 762, in _run_text_translation
    text_regions = await super()._run_text_translation(ctx)
  File "/root/manga-image-translator/manga_translator/manga_translator.py", line 527, in _run_text_translation
    await dispatch_translation(ctx.translator,
  File "/root/manga-image-translator/manga_translator/translators/__init__.py", line 123, in dispatch
    queries = await translator.translate('auto', tgt_lang, queries, use_mtpe)
  File "/root/manga-image-translator/manga_translator/translators/common.py", line 183, in translate
    _translations = await self._translate(*self.parse_language_codes(from_lang, to_lang, fatal=True), queries)
  File "/root/manga-image-translator/manga_translator/translators/google.py", line 157, in _translate
    translation = await self._translate_query(from_lang, to_lang, '\n'.join(lang_queries))
  File "/root/manga-image-translator/manga_translator/translators/google.py", line 200, in _translate_query
    raise encountered_exception
  File "/root/manga-image-translator/manga_translator/translators/google.py", line 194, in _translate_query
    return await self._request_and_parse_translation(query, to_lang, from_lang)
  File "/root/manga-image-translator/manga_translator/translators/google.py", line 204, in _request_and_parse_translation
    data, response = await self._request_translation(query, to_lang, from_lang)
  File "/root/manga-image-translator/manga_translator/translators/google.py", line 315, in _request_translation
    r = await self.client.post(url, params=params, data=data)
  File "/root/miniconda3/lib/python3.8/site-packages/httpx/_client.py", line 1374, in post
    return await self.request(
  File "/root/miniconda3/lib/python3.8/site-packages/httpx/_client.py", line 1147, in request
    response = await self.send(
  File "/root/miniconda3/lib/python3.8/site-packages/httpx/_client.py", line 1168, in send
    response = await self.send_handling_redirects(
  File "/root/miniconda3/lib/python3.8/site-packages/httpx/_client.py", line 1195, in send_handling_redirects
    response = await self.send_handling_auth(
  File "/root/miniconda3/lib/python3.8/site-packages/httpx/_client.py", line 1232, in send_handling_auth
    response = await self.send_single_request(request, timeout)
  File "/root/miniconda3/lib/python3.8/site-packages/httpx/_client.py", line 1264, in send_single_request
    ) = await transport.request(
  File "/root/miniconda3/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 152, in request
    response = await connection.request(
  File "/root/miniconda3/lib/python3.8/site-packages/httpcore/_async/connection.py", line 65, in request
    self.socket = await self._open_socket(timeout)
  File "/root/miniconda3/lib/python3.8/site-packages/httpcore/_async/connection.py", line 85, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/root/miniconda3/lib/python3.8/site-packages/httpcore/_backends/auto.py", line 38, in open_tcp_stream
    return await self.backend.open_tcp_stream(hostname, port, ssl_context, timeout)
  File "/root/miniconda3/lib/python3.8/site-packages/httpcore/_backends/asyncio.py", line 233, in open_tcp_stream
    return SocketStream(
  File "/root/miniconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/miniconda3/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.ConnectTimeout
Restarting translator process
[web_client] Namespace(align_center=False, align_left=False, align_right=False, attempts=0, box_threshold=0.7, colorization_size=576, colorizer=None, denoise_sigma=30, dest='', det_auto_rotate=False, det_gamma_correct=False, det_invert=False, det_rotate=False, detection_size=1536, detector='default', filter_text=None, font_color=None, font_path='', font_size=None, font_size_minimum=-1, font_size_offset=0, force_horizontal=False, force_vertical=False, format=None, gimp_font='Sans-serif', gpt_config=None, host='127.0.0.1', ignore_bubble=0, ignore_errors=False, inpainter='lama_large', inpainting_precision='fp32', inpainting_size=2048, input=None, kernel_size=3, line_spacing=None, lowercase=False, manga2eng=False, mask_dilation_offset=0, min_text_length=0, mode='web_client', model_dir=None, no_hyphenation=False, no_text_lang_skip=False, nonce='6d3996aad97034bccfb8c4051742d537', ocr='48px', overwrite=False, port=5003, prep_manual=False, revert_upscaling=False, save_quality=100, save_text=False, save_text_file='', selective_translation=None, skip_lang=None, skip_no_text=False, target_lang='CHS', text_threshold=0.5, translator='google', translator_chain=None, unclip_ratio=2.3, uppercase=False, upscale_ratio=None, upscaler='esrgan', use_gpu=True, use_gpu_limited=False, use_mocr_merge=False, use_mtpe=False, verbose=True, ws_url='ws://localhost:5000')
[web_client] Running in web_client mode
[web_client] Waiting for translation tasks
```

**Comment by starise-wg** [comment]
找到原因了：默认用的是google翻译，我的服务器在国内，由于网络原因，无法访问google翻译，所以存在超时，可以使用指定youdao进行翻译`python -m manga_translator --verbose --mode web --use-gpu --translator=youdao ` 即可
