### ISSUE TITLE
[Bug]: 使用第三方api报错

### ISSUE THREAD

**Issue by 55hhdd** [zyddnys/manga-image-translator#644]
### Issue

使用第三方api报错
这是.env的配置
![QQ图片20240615163014](https://github.com/zyddnys/manga-image-translator/assets/172888608/e67b295e-03e5-4811-9552-abae1c3ba771)

### Command Line Arguments

```Shell
python -m manga_translator -v --mode web
```

### Console logs

```Shell
ERROR: [web_client] APIConnectionError: Error communicating with OpenAI
Traceback (most recent call last):
  File "D:\Python\Lib\site-packages\aiohttp\connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "D:\Python\Lib\asyncio\base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\Python\Lib\asyncio\proactor_events.py", line 727, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\windows_events.py", line 803, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python\Lib\site-packages\openai\api_requestor.py", line 668, in arequest_raw
    result = await session.request(**request_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\aiohttp\connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "D:\Python\Lib\site-packages\aiohttp\connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\aiohttp\connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:8080 ssl:default [远程计算机拒绝网络连 接。]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\git\manga-image-translator\manga_translator\__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "D:\Python\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\git\manga-image-translator\manga_translator\__main__.py", line 50, in dispatch
    await translator.listen(args_dict)
  File "D:\git\manga-image-translator\manga_translator\manga_translator.py", line 750, in listen
    await self.translate_path(self._result_path('input.jpg'), self._result_path('final.jpg'),
  File "D:\git\manga-image-translator\manga_translator\manga_translator.py", line 154, in translate_path
    await self.translate_file(path, _dest, params)
  File "D:\git\manga-image-translator\manga_translator\manga_translator.py", line 205, in translate_file
    return await self._translate_file(path, dest, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git\manga-image-translator\manga_translator\manga_translator.py", line 248, in _translate_file
    ctx = await self.translate(img, ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git\manga-image-translator\manga_translator\manga_translator.py", line 305, in translate
    return await self._translate(ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git\manga-image-translator\manga_translator\manga_translator.py", line 425, in _translate
    ctx.text_regions = await self._run_text_translation(ctx)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git\manga-image-translator\manga_translator\manga_translator.py", line 762, in _run_text_translation
    text_regions = await super()._run_text_translation(ctx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git\manga-image-translator\manga_translator\manga_translator.py", line 527, in _run_text_translation
    await dispatch_translation(ctx.translator,
  File "D:\git\manga-image-translator\manga_translator\translators\__init__.py", line 123, in dispatch
    queries = await translator.translate('auto', tgt_lang, queries, use_mtpe)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git\manga-image-translator\manga_translator\translators\common.py", line 183, in translate
    _translations = await self._translate(*self.parse_language_codes(from_lang, to_lang, fatal=True), queries)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git\manga-image-translator\manga_translator\translators\chatgpt.py", line 150, in _translate
    response = await request_task
               ^^^^^^^^^^^^^^^^^^
  File "D:\git\manga-image-translator\manga_translator\translators\chatgpt.py", line 274, in _request_translation
    response = await openai.ChatCompletion.acreate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\api_requestor.py", line 372, in arequest
    result = await self.arequest_raw(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\api_requestor.py", line 685, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
Restarting translator process
```

**Comment by zyddnys** [comment]
是第三方api的问题
