### ISSUE TITLE
[Bug]: Some trouble running the script on windows

### ISSUE THREAD

**Issue by VoQZHD** [zyddnys/manga-image-translator#650]
### Issue

ImportError: numpy.core.multiarray failed to import

installed using the first pip method

### Command Line Arguments

```Shell
anything
```

### Console logs

```Shell
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "S:\Scanlation\manga-image-translator\manga_translator\__init__.py", line 7, in <module>
    from .manga_translator import *
  File "S:\Scanlation\manga-image-translator\manga_translator\manga_translator.py", line 5, in <module>
    import cv2
  File "S:\Scanlation\venv\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "S:\Scanlation\venv\Lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "S:\Scanlation\manga-image-translator\manga_translator\__init__.py", line 7, in <module>
    from .manga_translator import *
  File "S:\Scanlation\manga-image-translator\manga_translator\manga_translator.py", line 5, in <module>
    import cv2
  File "S:\Scanlation\venv\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "S:\Scanlation\venv\Lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: numpy.core.multiarray failed to import
```

**Comment by 77degrees** [comment]
numpy got updated to 2.0 and py3landid added support for numpy 2.0. Try the below, and it should work; it did for me. 

pip install py3landid==0.2.2
pip install numpy==1.23.5
