### ISSUE TITLE
[Bug]: ERROR: [web_client] AttributeError: module 'openai' has no attribute 'AsyncOpenAI'

### ISSUE THREAD

**Issue by Ctory-Nily** [zyddnys/manga-image-translator#664]
### Issue

今天更新了docker镜像，发现作者2天前更新了镜像然后本来可以部署成功的启动文件报错了
ERROR: [web_client] AttributeError: module 'openai' has no attribute 'AsyncOpenAI'

### Command Line Arguments

```Shell
version: "3.8"
name: manga_image_translator
services:
  manga_image_translator:
    image: zyddnys/manga-image-translator:main
    container_name: manga_image_translator_gpu
    command: --manga2eng -v --mode web --host=0.0.0.0 --port=5003 --use-gpu
    volumes:
      - ./result:/app/result
    ports:
      - 5003:5003
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"
              capabilities: ["gpu"]
```

### Console logs

```Shell
2024-07-01 23:31:04 manga_image_translator_gpu  | [web_client] Running in web_client mode
2024-07-01 23:31:04 manga_image_translator_gpu  | [web_client] Waiting for translation tasks
2024-07-01 23:31:04 manga_image_translator_gpu  | ERROR: [web_client] AttributeError: module 'openai' has no attribute 'AsyncOpenAI'
2024-07-01 23:31:04 manga_image_translator_gpu  | Traceback (most recent call last):
2024-07-01 23:31:04 manga_image_translator_gpu  |   File "/app/manga_translator/__main__.py", line 73, in <module>
2024-07-01 23:31:04 manga_image_translator_gpu  |     loop.run_until_complete(dispatch(args))
2024-07-01 23:31:04 manga_image_translator_gpu  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2024-07-01 23:31:04 manga_image_translator_gpu  |     return future.result()
2024-07-01 23:31:04 manga_image_translator_gpu  |   File "/app/manga_translator/__main__.py", line 50, in dispatch
2024-07-01 23:31:04 manga_image_translator_gpu  |     await translator.listen(args_dict)
2024-07-01 23:31:04 manga_image_translator_gpu  |   File "/app/manga_translator/manga_translator.py", line 726, in listen
2024-07-01 23:31:04 manga_image_translator_gpu  |     await self._init_connection()
2024-07-01 23:31:04 manga_image_translator_gpu  |   File "/app/manga_translator/manga_translator.py", line 679, in _init_connection
2024-07-01 23:31:04 manga_image_translator_gpu  |     get_translator(key)
2024-07-01 23:31:04 manga_image_translator_gpu  |   File "/app/manga_translator/translators/__init__.py", line 54, in get_translator
2024-07-01 23:31:04 manga_image_translator_gpu  |     translator_cache[key] = translator(*args, **kwargs)
2024-07-01 23:31:04 manga_image_translator_gpu  |   File "/app/manga_translator/translators/chatgpt.py", line 57, in __init__
2024-07-01 23:31:04 manga_image_translator_gpu  |     self.client = openai.AsyncOpenAI()
2024-07-01 23:31:04 manga_image_translator_gpu  | AttributeError: module 'openai' has no attribute 'AsyncOpenAI'
2024-07-01 23:31:05 manga_image_translator_gpu  | Restarting translator process
2024-07-01 23:31:07 manga_image_translator_gpu  | [web_client] Namespace(mode='web_client', input=None, dest='', target_lang='CHS', verbose=True, format=None, attempts=0, ignore_errors=False, overwrite=False, skip_no_text=False, model_dir=None, skip_lang=None, use_gpu=True, use_gpu_limited=False, detector='default', ocr='48px', use_mocr_merge=False, inpainter='lama_large', upscaler='esrgan', upscale_ratio=None, colorizer=None, translator='google', translator_chain=None, selective_translation=None, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, min_text_length=0, no_text_lang_skip=False, inpainting_size=2048, inpainting_precision='fp32', colorization_size=576, denoise_sigma=30, mask_dilation_offset=0, font_size=None, font_size_offset=0, font_size_minimum=-1, font_color=None, line_spacing=None, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, no_hyphenation=False, manga2eng=False, gpt_config=None, use_mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', gimp_font='Sans-serif', host='0.0.0.0', port=5003, nonce='462bbe40f5b5f11d42b97695a3f493f2', ws_url='ws://localhost:5000', save_quality=100, ignore_bubble=0, kernel_size=3)
2024-07-01 23:31:07 manga_image_translator_gpu  | [web_client] Running in web_client mode
2024-07-01 23:31:07 manga_image_translator_gpu  | [web_client] Waiting for translation tasks
2024-07-01 23:31:07 manga_image_translator_gpu  | ERROR: [web_client] AttributeError: module 'openai' has no attribute 'AsyncOpenAI'
2024-07-01 23:31:07 manga_image_translator_gpu  | Traceback (most recent call last):
2024-07-01 23:31:07 manga_image_translator_gpu  |   File "/app/manga_translator/__main__.py", line 73, in <module>
2024-07-01 23:31:07 manga_image_translator_gpu  |     loop.run_until_complete(dispatch(args))
2024-07-01 23:31:07 manga_image_translator_gpu  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2024-07-01 23:31:07 manga_image_translator_gpu  |     return future.result()
2024-07-01 23:31:07 manga_image_translator_gpu  |   File "/app/manga_translator/__main__.py", line 50, in dispatch
2024-07-01 23:31:07 manga_image_translator_gpu  |     await translator.listen(args_dict)
2024-07-01 23:31:07 manga_image_translator_gpu  |   File "/app/manga_translator/manga_translator.py", line 726, in listen
2024-07-01 23:31:07 manga_image_translator_gpu  |     await self._init_connection()
2024-07-01 23:31:07 manga_image_translator_gpu  |   File "/app/manga_translator/manga_translator.py", line 679, in _init_connection
2024-07-01 23:31:07 manga_image_translator_gpu  |     get_translator(key)
2024-07-01 23:31:07 manga_image_translator_gpu  |   File "/app/manga_translator/translators/__init__.py", line 54, in get_translator
2024-07-01 23:31:07 manga_image_translator_gpu  |     translator_cache[key] = translator(*args, **kwargs)
2024-07-01 23:31:07 manga_image_translator_gpu  |   File "/app/manga_translator/translators/chatgpt.py", line 57, in __init__
2024-07-01 23:31:07 manga_image_translator_gpu  |     self.client = openai.AsyncOpenAI()
2024-07-01 23:31:07 manga_image_translator_gpu  | AttributeError: module 'openai' has no attribute 'AsyncOpenAI'
2024-07-01 23:31:08 manga_image_translator_gpu  | Restarting translator process
```

**Comment by Ctory-Nily** [comment]
https://github.com/zyddnys/manga-image-translator/issues/653

我找到解决方法了

**Comment by Ctory-Nily** [comment]
https://github.com/zyddnys/manga-image-translator/issues/653

我找到解决方法了
