### ISSUE TITLE
[Bug]: 请问这是怎那么了

### ISSUE THREAD

**Issue by 253701** [zyddnys/manga-image-translator#669]
### Issue

ERROR: [web_client] OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
Traceback (most recent call last):
  File "L:\manhua\manga-image-translator-main\manga_translator\__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "C:\Users\ycy\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "L:\manhua\manga-image-translator-main\manga_translator\__main__.py", line 50, in dispatch
    await translator.listen(args_dict)
  File "L:\manhua\manga-image-translator-main\manga_translator\manga_translator.py", line 726, in listen
    await self._init_connection()
  File "L:\manhua\manga-image-translator-main\manga_translator\manga_translator.py", line 679, in _init_connection
    get_translator(key)
  File "L:\manhua\manga-image-translator-main\manga_translator\translators\__init__.py", line 54, in get_translator
    translator_cache[key] = translator(*args, **kwargs)
  File "L:\manhua\manga-image-translator-main\manga_translator\translators\chatgpt.py", line 57, in __init__
    self.client = openai.AsyncOpenAI()
  File "L:\manhua\manga-image-translator-main\venv\lib\site-packages\openai\_client.py", line 316, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable为什么一启动就连续不间断的报错这个，并且web网页找不到樱花模型的选项，而且任何翻译服务都报错，显示上传失败请重新上传，我是哪里搞错了吗，最开始部署完毕后提升升级什么openai 库，我就更新了一下，

**Comment by 253701** [comment]
![(S@ {Q%PSWW)U`J@)K5~W@4](https://github.com/zyddnys/manga-image-translator/assets/127170526/7d5222c5-96d6-4e4d-91f0-1c28f1a42f70)
![2_}FWEN6Y_8KRT(7D0ZXPOY](https://github.com/zyddnys/manga-image-translator/assets/127170526/e475e3cb-cd92-40b1-8fc4-dc620f47ef67)
![3 `1S @I5Z5U3){63B 2OJV](https://github.com/zyddnys/manga-image-translator/assets/127170526/1d404069-7fe4-4b14-bf40-2a550c321fd5)

**Comment by 253701** [comment]
![2_}FWEN6Y_8KRT(7D0ZXPOY](https://github.com/zyddnys/manga-image-translator/assets/127170526/5a9a72c3-e127-49a5-98ee-85aee3ea0ec7)

**Comment by 253701** [comment]
![(S@ {Q%PSWW)U`J@)K5~W@4](https://github.com/zyddnys/manga-image-translator/assets/127170526/f64d6f75-4a93-4a45-985a-9ef26cf06f9a)

**Comment by Ctory-Nily** [comment]
没有设置OPENAI_API_KEY 环境变量，没有读取到这个环境变量
https://github.com/zyddnys/manga-image-translator/issues/665#issuecomment-2211136092

**Comment by 253701** [comment]
> 没有设置OPENAI_API_KEY 环境变量，没有读取到这个环境变量 [#665 (comment)](https://github.com/zyddnys/manga-image-translator/issues/665#issuecomment-2211136092)

我没有OPENAI_API_KEY，只想用离线本地模型跑，但是现在任何一个翻译都用不了

**Comment by 253701** [comment]
> 没有设置OPENAI_API_KEY 环境变量，没有读取到这个环境变量 [#665 (comment)](https://github.com/zyddnys/manga-image-translator/issues/665#issuecomment-2211136092)

已解决，运行时不要挂梯子
