### ISSUE TITLE
[Bug]: centOS7安装后，也会提示：module 'openai' has no attribute 'AsyncOpenAI'

### ISSUE THREAD

**Issue by da1995** [zyddnys/manga-image-translator#670]
### Issue

新安装的，启动就这样子，centOS好像更新openai库还挺费劲，捣鼓一天无果，无法启动

### Console logs

```Shell
[web_client] Namespace(mode='web_client', input=None, dest='', target_lang='CHS', verbose=True, format=None, attempts=0, ignore_errors=False, overwrite=False, skip_no_text=False, model_dir=None, skip_lang=None, use_gpu=False, use_gpu_limited=False, detector='default', ocr='48px', use_mocr_merge=False, inpainter='lama_large', upscaler='esrgan', upscale_ratio=None, colorizer=None, translator='google', translator_chain=None, selective_translation=None, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, min_text_length=0, no_text_lang_skip=False, inpainting_size=2048, inpainting_precision='fp32', colorization_size=576, denoise_sigma=30, mask_dilation_offset=0, font_size=None, font_size_offset=0, font_size_minimum=-1, font_color=None, line_spacing=None, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, no_hyphenation=False, manga2eng=False, gpt_config=None, use_mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', gimp_font='Sans-serif', host='0.0.0.0', port=5003, nonce='011037840d987d3c70051b53da187c69', ws_url='ws://localhost:5000', save_quality=100, ignore_bubble=0, kernel_size=3)
[web_client] Running in web_client mode
[web_client] Waiting for translation tasks
ERROR: [web_client] AttributeError: module 'openai' has no attribute 'AsyncOpenAI'
Traceback (most recent call last):
  File "/app/manga_translator/__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/manga_translator/__main__.py", line 50, in dispatch
    await translator.listen(args_dict)
  File "/app/manga_translator/manga_translator.py", line 726, in listen
    await self._init_connection()
  File "/app/manga_translator/manga_translator.py", line 679, in _init_connection
    get_translator(key)
  File "/app/manga_translator/translators/__init__.py", line 54, in get_translator
    translator_cache[key] = translator(*args, **kwargs)
  File "/app/manga_translator/translators/chatgpt.py", line 57, in __init__
    self.client = openai.AsyncOpenAI()
AttributeError: module 'openai' has no attribute 'AsyncOpenAI'
Restarting translator process
```

**Comment by findingwch** [comment]
可以尝试更新openai版本 pip install --upgrade openai

**Comment by da1995** [comment]
> 可以尝试更新 openai 版本 pip install --upgrade openai

尝试更新无果，才来发帖求助的

**Comment by hakure890** [comment]
我也是同樣的問題...

**Comment by zyddnys** [comment]
pip install -U openai

**Comment by zyddnys** [comment]
https://github.com/zyddnys/manga-image-translator/issues/653
