### ISSUE TITLE
[Bug]: CUDA or Metal compatible device could not be found in torch whilst --use-gpu args was set.

### ISSUE THREAD

**Issue by cycham0** [zyddnys/manga-image-translator#712]
### Issue

Mine is Windows 11, with CUDA 12.1, it is working under conda(manga) + virtualenv (venv)
It cannot not work with gpu. Here is the infomation.

> (manga) (venv) PS C:\Users\chamc\Documents\GitHub\manga-image-translator> nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2023 NVIDIA Corporation
> Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
> Cuda compilation tools, release 12.1, V12.1.66
> Build cuda_12.1.r12.1/compiler.32415258_0

```
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No CUDA device found")
```

> 2.4.1+cu121
True
1
NVIDIA GeForce GTX 950

### Command Line Arguments

```Shell
(manga) (venv) PS C:\Users\chamc\Documents\GitHub\manga-image-translator> python -m manga_translator -v --translator=papago --use-gpu -l CHS  -i "G:\cough\test"
```

### Console logs

```Shell
[batch] Namespace(mode='batch', input=['G:\\cough\\test'], dest='', target_lang='CHS', verbose=True, format=None, attempts=0, ignore_errors=False, overwrite=False, skip_no_text=False, model_dir=None, skip_lang=None, use_gpu=True, use_gpu_limited=False, detector='default', ocr='48px', use_mocr_merge=False, inpainter='lama_large', upscaler='esrgan', upscale_ratio=None, colorizer=None, translator='papago', translator_chain=None, selective_translation=None, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, min_text_length=0, no_text_lang_skip=False, inpainting_size=2048, inpainting_precision='fp32', colorization_size=576, denoise_sigma=30, mask_dilation_offset=0, disable_font_border=False, font_size=None, font_size_offset=0, font_size_minimum=-1, font_color=None, line_spacing=None, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, no_hyphenation=False, manga2eng=False, gpt_config=None, use_mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', gimp_font='Sans-serif', host='127.0.0.1', port=5003, nonce='', ws_url='ws://localhost:5000', save_quality=100, ignore_bubble=0, kernel_size=3)
[batch] Running in batch mode
ERROR: [batch] Exception: CUDA or Metal compatible device could not be found in torch whilst --use-gpu args was set.
Is the correct pytorch version installed? (See https://pytorch.org/)
Traceback (most recent call last):
  File "C:\Users\chamc\Documents\GitHub\manga-image-translator\manga_translator\__main__.py", line 73, in <module>
    loop.run_until_complete(dispatch(args))
  File "C:\Users\chamc\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\chamc\Documents\GitHub\manga-image-translator\manga_translator\__main__.py", line 32, in dispatch
    translator = MangaTranslator(args_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chamc\Documents\GitHub\manga-image-translator\manga_translator\manga_translator.py", line 88, in __init__
    self.parse_init_params(params)
  File "C:\Users\chamc\Documents\GitHub\manga-image-translator\manga_translator\manga_translator.py", line 108, in parse_init_params
    raise Exception(
Exception: CUDA or Metal compatible device could not be found in torch whilst --use-gpu args was set.
Is the correct pytorch version installed? (See https://pytorch.org/)
```

**Comment by esciron** [comment]
Same thing happening to me with a 4090 in windows 10

**Comment by jokester** [comment]
the torch packages installed from pypi may not have CUDA support

maybe try https://pytorch.org/get-started/locally/ with custom index for your platform

**Comment by esciron** [comment]
> the torch packages installed from pypi may not have CUDA support
> 
> maybe try https://pytorch.org/get-started/locally/ with custom index for your platform

Yeah, installing again pytorch directly via pip with the cuda support fixed it.
The thing is that I have automatic1111, comfyui etc and everything worked fine, I'm gonna assume there's something going on with windows and local installs of those two apps that maybe use a different version than the one that windows installs with pip by default.
