### ISSUE TITLE
[Bug]: error while running in google colab

### ISSUE THREAD

**Issue by rsaurav12** [zyddnys/manga-image-translator#758]
### Issue

I'm running this in google colab

Translation is working fine but output is not generating and giving me this error

### Command Line Arguments

```Shell
!python -m manga_translator -v --use-gpu local -i /content/e.jpg -o /content/o
```

### Console logs

```Shell
[render] font_size_minimum 15
[render]: 100% 9/9 [00:01<00:00,  6.59it/s]
ERROR: [local] AttributeError: 'MangaTranslatorLocal' object has no attribute 'textlines'
Traceback (most recent call last):
  File "/content/manga-image-translator/manga_translator/__main__.py", line 89, in <module>
    asyncio.run(dispatch(args))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/content/manga-image-translator/manga_translator/__main__.py", line 41, in dispatch
    for textline in translator.textlines:
AttributeError: 'MangaTranslatorLocal' object has no attribute 'textlines
```

**Comment by frederik-uni** [comment]
demo mode in __main__.py is missing the try catch. is not related to collab. this is the same issue as #741, but it was only implemented for batch mode as it seems

**Comment by mugnimaestra** [comment]
For anyone hitting Colab issues — the notebook has been updated in #1129 with the correct server setup and CUDA fix.
