### ISSUE TITLE
[Bug]: Inpainter not working

### ISSUE THREAD

**Issue by eren-ay** [zyddnys/manga-image-translator#760]
### Issue

i try lama_large and default and doesn't work

### Console logs

```Shell
nternal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/server/main.py", line 84, in json_form
    ctx = await get_ctx(req, Config.parse_raw(config), img)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/server/request_extraction.py", line 50, in get_ctx
    return await wait_in_queue(task, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/server/myqueue.py", line 96, in wait_in_queue
    result = await instance.sent(task.image, task.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/server/instance.py", line 20, in sent
    return await fetch_data("http://"+self.ip+":"+str(self.port)+"/simple_execute/translate", image, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/server/sent_data_internal.py", line 32, in fetch_data
    raise HTTPException(response.status, detail=response.text())
fastapi.exceptions.HTTPException: 500: <coroutine object ClientResponse.text at 0x7dc3f304db60>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 59, in wrapped_app
    response = await handler(conn, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/fastapi/exception_handlers.py", line 15, in http_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/responses.py", line 180, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/responses.py", line 43, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/eren/project/mangaTranslator/manga-image-translator/venv/lib/python3.12/site-packages/starlette/responses.py", line 183, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
```

**Comment by eren-ay** [comment]
error _infer function all inpainters 
If we redefine inpainting_size manually within the _infer function, it continues to work
like inpainting_size=1024

**Comment by frederik-uni** [comment]
I only used the none mode bc of performance while testing. That’s why I didn’t notice
