### ISSUE TITLE
[Bug]: No module named 'colorama'

### ISSUE THREAD

**Issue by NoteBlockMR** [zyddnys/manga-image-translator#769]
### Issue

![Screenshot_2](https://github.com/user-attachments/assets/7d2df8a8-f36f-4ddd-9276-aacf36cbcd1b)

The pip install -r requirements.txt command says the module is not installed even though I entered it

Test Python Version 3.10.6

### Command Line Arguments

```Shell
python -m manga_translator local -i manga1 --use-gpu --config-file config.json
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\AITranslator2\manga-image-translator2\manga_translator\__init__.py", line 1, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
```

**Comment by BlaskKilt** [comment]
pip install colorama have you tried it?

**Comment by BlaskKilt** [comment]
u can try 

 ```python
import colorama

print(colorama.Fore.RED + "Colorama is installed successfully!" + colorama.Style.RESET_ALL)

if u want to know if its installed correctly

**Comment by NoteBlockMR** [comment]
> `pip install colorama ` have you tried it?

I installed it obviously
but it doesn't work

**Comment by popcion** [comment]
If you are using venv, did you directly copy the venv environment to other folders? If so, installing other libraries will install them in the source folder, and you will need to re-download every time you create an environment variable. Don't copy directly for convenience.
