### ISSUE TITLE
[Bug]: RuntimeError: Unable to configure default ndarray.__repr__

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#775]
### Issue

RuntimeError: Unable to configure default ndarray.__repr__

### Command Line Arguments

```Shell
(manga-image-translator) F:\manga-image-translator>python -m manga_translator -v --mode web --use-cuda --font-path=fonts/anime_ace.ttf
```

### Console logs

```Shell
(manga-image-translator) F:\manga-image-translator>python -m manga_translator -v --mode web --use-cuda --font-path=fonts/anime_ace.ttf
Traceback (most recent call last):
  File "F:\1\envs\manga-image-translator\lib\site-packages\numpy\_core\arrayprint.py", line 34, in <module>
    from . import numerictypes as _nt
  File "F:\1\envs\manga-image-translator\lib\site-packages\numpy\_core\numerictypes.py", line 102, in <module>
    from ._type_aliases import (
  File "F:\1\envs\manga-image-translator\lib\site-packages\numpy\_core\_type_aliases.py", line 38, in <module>
    allTypes[_abstract_type_name] = getattr(ma, _abstract_type_name)
AttributeError: module 'numpy.core.multiarray' has no attribute 'inexact'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\1\envs\manga-image-translator\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "F:\1\envs\manga-image-translator\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "F:\1\envs\manga-image-translator\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "F:\manga-image-translator\manga_translator\__init__.py", line 7, in <module>
    from .manga_translator import *
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 25, in <module>
    from .detection import dispatch as dispatch_detection, prepare as prepare_detection
  File "F:\manga-image-translator\manga_translator\detection\__init__.py", line 3, in <module>
    from .default import DefaultDetector
  File "F:\manga-image-translator\manga_translator\detection\default.py", line 10, in <module>
    from .default_utils import imgproc, dbnet_utils, craft_utils
  File "F:\manga-image-translator\manga_translator\detection\default_utils\imgproc.py", line 8, in <module>
    from skimage import io
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "F:\1\envs\manga-image-translator\lib\site-packages\lazy_loader\__init__.py", line 79, in __getattr__
    return importlib.import_module(f"{package_name}.{name}")
  File "F:\1\envs\manga-image-translator\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "F:\1\envs\manga-image-translator\lib\site-packages\skimage\io\__init__.py", line 11, in <module>
    from ._io import *
  File "F:\1\envs\manga-image-translator\lib\site-packages\skimage\io\_io.py", line 8, in <module>
    from ..color.colorconv import rgb2gray, rgba2rgb
  File "F:\1\envs\manga-image-translator\lib\site-packages\skimage\color\colorconv.py", line 450, in <module>
    rgbcie_from_rgb = rgbcie_from_xyz @ xyz_from_rgb
  File "F:\1\envs\manga-image-translator\lib\site-packages\numpy\core\_internal.py", line 855, in array_ufunc_errmsg_formatter
    args_string = ', '.join(['{!r}'.format(arg) for arg in inputs] +
  File "F:\1\envs\manga-image-translator\lib\site-packages\numpy\core\_internal.py", line 855, in <listcomp>
    args_string = ', '.join(['{!r}'.format(arg) for arg in inputs] +
RuntimeError: Unable to configure default ndarray.__repr__
```

**Comment by frederik-uni** [comment]
please have a mock at the documentation

**Comment by My12123** [comment]
```python
(manga-image-translator) F:\manga-image-translator>cd server && python main.py --use-gpu
Traceback (most recent call last):
  File "F:\1\envs\manga-image-translator\lib\site-packages\numpy\_core\arrayprint.py", line 34, in <module>
    from . import numerictypes as _nt
  File "F:\1\envs\manga-image-translator\lib\site-packages\numpy\_core\numerictypes.py", line 102, in <module>
    from ._type_aliases import (
  File "F:\1\envs\manga-image-translator\lib\site-packages\numpy\_core\_type_aliases.py", line 38, in <module>
    allTypes[_abstract_type_name] = getattr(ma, _abstract_type_name)
AttributeError: module 'numpy.core.multiarray' has no attribute 'character'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\manga-image-translator\server\main.py", line 18, in <module>
    from manga_translator import Config
  File "F:\manga-image-translator\manga_translator\__init__.py", line 7, in <module>
    from .manga_translator import *
  File "F:\manga-image-translator\manga_translator\manga_translator.py", line 25, in <module>
    from .detection import dispatch as dispatch_detection, prepare as prepare_detection
  File "F:\manga-image-translator\manga_translator\detection\__init__.py", line 3, in <module>
    from .default import DefaultDetector
  File "F:\manga-image-translator\manga_translator\detection\default.py", line 10, in <module>
    from .default_utils import imgproc, dbnet_utils, craft_utils
  File "F:\manga-image-translator\manga_translator\detection\default_utils\imgproc.py", line 8, in <module>
    from skimage import io
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "F:\1\envs\manga-image-translator\lib\site-packages\lazy_loader\__init__.py", line 79, in __getattr__
    return importlib.import_module(f"{package_name}.{name}")
  File "F:\1\envs\manga-image-translator\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "F:\1\envs\manga-image-translator\lib\site-packages\skimage\io\__init__.py", line 11, in <module>
    from ._io import *
  File "F:\1\envs\manga-image-translator\lib\site-packages\skimage\io\_io.py", line 8, in <module>
    from ..color.colorconv import rgb2gray, rgba2rgb
  File "F:\1\envs\manga-image-translator\lib\site-packages\skimage\color\colorconv.py", line 450, in <module>
    rgbcie_from_rgb = rgbcie_from_xyz @ xyz_from_rgb
  File "F:\1\envs\manga-image-translator\lib\site-packages\numpy\core\_internal.py", line 855, in array_ufunc_errmsg_formatter
    args_string = ', '.join(['{!r}'.format(arg) for arg in inputs] +
  File "F:\1\envs\manga-image-translator\lib\site-packages\numpy\core\_internal.py", line 855, in <listcomp>
    args_string = ', '.join(['{!r}'.format(arg) for arg in inputs] +
RuntimeError: Unable to configure default ndarray.__repr__
```

**Comment by My12123** [comment]
```
Open the link to use manga-image-translator! ->  https://mdvtj6r2e3i-496ff2e9c6d22116-5003-colab.googleusercontent.com/
2024-12-07 08:48:43.438726: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-12-07 08:48:43.455222: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-12-07 08:48:43.461000: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-07 08:48:43.475888: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-07 08:48:44.750488: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
usage: manga_translator [-h] [-v] [--attempts ATTEMPTS] [--ignore-errors] [--model-dir MODEL_DIR]
                        [--use-gpu | --use-gpu-limited] [--font-path FONT_PATH]
                        [--pre-dict PRE_DICT] [--post-dict POST_DICT] [--kernel-size KERNEL_SIZE]
                        {local,ws,shared,config-help} ...
manga_translator: error: argument --model-dir: No such directory: "web"
```
