### ISSUE TITLE
如何用pyinstaller把这个项目打包成单个CLI程序

### ISSUE THREAD

**Issue by blacklein** [zyddnys/manga-image-translator#79]
我试着用`pyinstaller -F translate_demo.py`打包了下，打包成功了，150MB，但运行打包好的CLI报错了

```
[27178] WARNING: file already exists but should not: /var/folders/cl/wp12ygrn1cz9gkrlh8n5tls00000gn/T/_MEIC3WwOg/torch/_C.cpython-310-darwin.so
[27178] WARNING: file already exists but should not: /var/folders/cl/wp12ygrn1cz9gkrlh8n5tls00000gn/T/_MEIC3WwOg/torch/_C_flatbuffer.cpython-310-darwin.so
[27178] WARNING: file already exists but should not: /var/folders/cl/wp12ygrn1cz9gkrlh8n5tls00000gn/T/_MEIC3WwOg/torch/_dl.cpython-310-darwin.so
['/var/folders/cl/wp12ygrn1cz9gkrlh8n5tls00000gn/T/_MEIC3WwOg/base_library.zip', '/private/var/folders/cl/wp12ygrn1cz9gkrlh8n5tls00000gn/T/_MEIC3WwOg/cv2', '/var/folders/cl/wp12ygrn1cz9gkrlh8n5tls00000gn/T/_MEIC3WwOg/lib-dynload', '/var/folders/cl/wp12ygrn1cz9gkrlh8n5tls00000gn/T/_MEIC3WwOg']
Traceback (most recent call last):
  File "translate_demo.py", line 5, in <module>
    import cv2
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib/__init__.py", line 126, in import_module
    if sys.path[0] == BASE_DIR or os.path.realpath(sys.path[0]) == BASE_DIR:
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "cv2/__init__.py", line 76, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
[27179] Failed to execute script 'translate_demo' due to unhandled exception!
```

**Comment by zyddnys** [comment]
确保opencv安装对了
